#!/usr/bin/env python3
"""Inject example sentences into key crypto-words-1000.json entries."""
import json, pathlib

EXAMPLES = {
    "blockchain":        "Ethereum is the second-largest blockchain by market capitalization.",
    "consensus":         "Bitcoin uses proof-of-work consensus to agree on the valid chain.",
    "hash":              "Every block contains the hash of the previous block, forming a chain.",
    "node":              "Running a full node lets you independently verify the entire blockchain.",
    "validator":         "Validators stake 32 ETH to participate in Ethereum block proposals.",
    "transaction":       "Each on-chain transaction is signed with the sender's private key.",
    "smart contract":    "The smart contract automatically releases funds once delivery is confirmed.",
    "wallet":            "A hardware wallet stores your private keys offline for maximum security.",
    "seed phrase":       "Never share your seed phrase — it gives full control of your funds.",
    "mnemonic":          "A 12-word mnemonic can restore your wallet on any compatible device.",
    "proof of work":     "Bitcoin's proof of work requires miners to solve computationally expensive puzzles.",
    "proof of stake":    "Ethereum switched to proof of stake in the Merge, cutting energy use by 99%.",
    "cryptography":      "Modern blockchain security relies on public-key cryptography and hash functions.",
    "digital signature": "A digital signature proves that a transaction was authorized by the key owner.",
    "fork":              "A contentious fork can split a blockchain community into two competing chains.",
    "hard fork":         "Ethereum Classic was created after a hard fork over the DAO hack in 2016.",
    "soft fork":         "SegWit was deployed as a soft fork, remaining backward-compatible with old nodes.",
    "mempool":           "Pending transactions wait in the mempool before miners include them in a block.",
    "halving":           "Bitcoin's halving reduces the block reward by 50% roughly every four years.",
    "tokenomics":        "Strong tokenomics align incentives between users, developers, and investors.",
    "whitepaper":        "Satoshi Nakamoto published the Bitcoin whitepaper in October 2008.",
    "NFT":               "The artist sold an NFT of her digital painting for 10 ETH at auction.",
    "DeFi":              "DeFi protocols let anyone lend, borrow, and trade without a bank.",
    "AMM":               "Uniswap's AMM prices tokens automatically using the constant-product formula.",
    "liquidity pool":    "LPs deposit token pairs into a liquidity pool and earn a share of trading fees.",
    "stablecoin":        "Merchants prefer stablecoins to avoid cryptocurrency price volatility.",
    "DAO":               "The DAO voted on-chain to allocate treasury funds to a new development grant.",
    "gas":               "High network demand pushes gas prices up, making transactions more expensive.",
    "EVM":               "Any EVM-compatible chain can run Ethereum smart contracts without modification.",
    "ERC-20":            "Most DeFi tokens follow the ERC-20 standard for seamless wallet compatibility.",
    "ERC-721":           "CryptoPunks and Bored Apes are ERC-721 NFT collections on Ethereum.",
    "airdrop":           "Uniswap's 400 UNI airdrop surprised early users with unexpected rewards.",
    "yield farming":     "Yield farmers move capital between protocols to maximize APY.",
    "staking":           "Staking ETH earns rewards while helping secure the Ethereum network.",
    "bridge":            "Cross-chain bridges let you move assets between Ethereum and Polygon.",
    "oracle":            "Chainlink oracles supply DeFi protocols with tamper-resistant price feeds.",
    "flash loan":        "The attacker used a flash loan to manipulate prices and drain the pool.",
    "reentrancy":        "The 2016 DAO hack exploited a reentrancy bug to drain 3.6 million ETH.",
    "slippage":          "Setting a 0.5% slippage tolerance protects against price movement during swaps.",
    "impermanent loss":  "LPs suffer impermanent loss when the prices of deposited tokens diverge.",
    "liquidation":       "When collateral drops below 150%, the borrowing position faces liquidation.",
    "collateral":        "Borrowers deposit ETH as collateral to mint DAI on MakerDAO.",
    "overcollateralized":"MakerDAO requires overcollateralized positions to maintain DAI's dollar peg.",
    "TVL":               "Aave's TVL surpassed $10 billion at the peak of the DeFi bull market.",
    "DEX":               "On a DEX you trade directly from your wallet without giving up custody.",
    "CEX":               "Binance is the largest CEX by daily trading volume.",
    "custody":           "Non-custodial wallets give you full control over your private keys.",
    "KYC":               "Most CEXs require KYC verification before allowing fiat currency withdrawals.",
    "AML":               "Crypto exchanges implement AML programs to detect and report suspicious activity.",
    "USDT":              "USDT is the most widely used stablecoin for trading pairs on exchanges.",
    "USDC":              "Circle's USDC is backed 1:1 by cash and short-term US Treasuries.",
    "DAI":               "DAI maintains its dollar peg through overcollateralized crypto vault positions.",
    "Uniswap":           "Uniswap pioneered the AMM model and became the largest DEX by volume.",
    "Aave":              "Aave lets users deposit assets to earn interest or borrow against collateral.",
    "Compound":          "Compound's cTokens automatically accrue interest for depositors over time.",
    "MakerDAO":          "MakerDAO governs the DAI stablecoin through MKR token holder votes.",
    "Curve Finance":     "Curve Finance specializes in low-slippage stable-to-stable token swaps.",
    "Lido":              "Lido lets users stake any amount of ETH and receive liquid stETH in return.",
    "liquid staking":    "Liquid staking tokens let you earn staking yield while staying liquid in DeFi.",
    "PayFi":             "PayFi protocols enable real-time cross-border payroll settlements using stablecoins.",
    "payment streaming": "With Superfluid, companies can stream salaries to employees second by second.",
    "tokenization":      "Real estate tokenization allows fractional ownership of physical property.",
    "RWA":               "RWA protocols are bringing billions in US Treasuries and bonds on-chain.",
    "MEV":               "MEV searchers profit by reordering transactions within an Ethereum block.",
    "front-running":     "Bots front-run large DEX trades by paying higher gas to jump the queue.",
    "sandwich attack":   "A sandwich attack places buy orders before and sell orders after a victim's trade.",
    "zero-knowledge proof": "ZK proofs let a prover convince a verifier without revealing any private data.",
    "Layer 2":           "Layer 2 solutions like Arbitrum reduce Ethereum fees by 10 to 100 times.",
    "rollup":            "Rollups batch hundreds of transactions into one proof posted to Ethereum.",
    "optimistic rollup": "Optimistic rollups assume transactions are valid unless challenged within 7 days.",
    "ZK rollup":         "ZK rollups use cryptographic proofs to instantly verify transaction batches.",
    "Arbitrum":          "Arbitrum is the largest optimistic rollup by TVL and transaction volume.",
    "Optimism":          "Optimism's Superchain vision aims to unify multiple OP Stack chains.",
    "zkSync":            "zkSync uses ZK proofs to offer cheap, fast Ethereum-compatible transactions.",
    "cross-chain":       "Cross-chain interoperability lets value flow freely between different blockchains.",
    "multisig":          "Gnosis Safe multisig requires M-of-N signers to approve each transaction.",
    "cold wallet":       "Storing large funds on a cold wallet protects against online hacks.",
    "hot wallet":        "A hot wallet is convenient but more exposed to phishing and malware.",
    "HODL":              "Long-term investors choose to HODL through market downturns rather than sell.",
    "bull market":       "During the 2021 bull market, Bitcoin reached an all-time high near $69,000.",
    "bear market":       "The 2022 bear market wiped out over 70% of the total crypto market cap.",
    "market cap":        "Bitcoin's market cap dominates the crypto sector at over 50% of total value.",
    "NAV":               "The ETF's NAV is calculated daily from the market value of its holdings.",
    "AUM":               "BlackRock's crypto fund AUM exceeded $20 billion within its first year.",
    "KYB":               "PayFi platforms run KYB checks before onboarding business borrowers.",
    "securitization":    "RWA securitization brings traditional financial asset structures onto the blockchain.",
    "trade receivable":  "Huma Finance lets businesses tokenize trade receivables for instant liquidity.",
    "PYUSD":             "PayPal launched PYUSD as its native stablecoin for commerce and Web3 payments.",
    "Solidity":          "Developers write Ethereum smart contracts in Solidity, a statically typed language.",
    "dApp":              "Uniswap is a dApp that runs entirely on Ethereum smart contracts.",
    "FOMO":              "FOMO drove retail investors to buy near the peak of the 2021 bull run.",
    "FUD":               "FUD about regulatory crackdowns caused a sharp market sell-off.",
    "governance token":  "Holding a governance token lets you vote on protocol upgrades and treasury use.",
    "vesting":           "Team tokens carry a 4-year vesting schedule to align long-term incentives.",
    "whitelist":         "Only whitelisted wallets could participate in the early-access token sale.",
    "snapshot":          "A snapshot of all holders was taken at block 18,000,000 to calculate airdrop amounts.",
    "on-chain":          "On-chain governance lets token holders vote directly through smart contracts.",
    "off-chain":         "Off-chain computation reduces gas costs by moving heavy logic outside the EVM.",
    "wrapped token":     "WBTC is a wrapped token that brings Bitcoin liquidity into Ethereum DeFi.",
    "interoperability":  "Polkadot is designed for blockchain interoperability between parachains.",
    "Ondo Finance":      "Ondo Finance tokenizes US Treasuries so DeFi users can earn real-world yields.",
    "Maple Finance":     "Maple Finance provides institutional-grade on-chain lending with transparent terms.",
    "invoice financing": "Invoice financing lets businesses unlock capital tied up in unpaid invoices.",
    "T+0 settlement":    "Blockchain enables T+0 settlement, replacing the traditional T+2 clearing cycle.",
    "Huma Finance":      "Huma Finance tokenizes trade receivables to give businesses instant liquidity.",
}

src = pathlib.Path(__file__).parent.parent / 'game' / 'crypto-words-1000.json'
words = json.loads(src.read_text(encoding='utf-8'))

updated = 0
for w in words:
    ex = EXAMPLES.get(w['word'])
    if ex and not w.get('ex'):
        w['ex'] = ex
        updated += 1

src.write_text(json.dumps(words, ensure_ascii=False, indent=2), encoding='utf-8')
print(f"Done. Added examples to {updated} entries. Total entries: {len(words)}.")
