#!/usr/bin/env python3
"""Generate daily-words-1000.json – high-frequency daily spoken English."""
import json, pathlib

WORDS = [
# ── 1. Greetings & Social (社交问候) ──────────────────────────────────────
{"word":"hello","zh":"你好","pos":"interj.","ipa":"","ex":"Hello! How are you doing today?"},
{"word":"goodbye","zh":"再见","pos":"interj.","ipa":"","ex":"Goodbye! Have a safe trip home."},
{"word":"see you","zh":"回头见","pos":"phr.","ipa":"","ex":"See you tomorrow at the office!"},
{"word":"nice to meet you","zh":"很高兴认识你","pos":"phr.","ipa":"","ex":"Nice to meet you. I'm Sarah from the marketing team."},
{"word":"how are you","zh":"你好吗","pos":"phr.","ipa":"","ex":"How are you? I haven't seen you in ages!"},
{"word":"I'm fine","zh":"我很好","pos":"phr.","ipa":"","ex":"I'm fine, thanks for asking. How about you?"},
{"word":"please","zh":"请","pos":"adv.","ipa":"","ex":"Could you please send me the report by Friday?"},
{"word":"thank you","zh":"谢谢","pos":"phr.","ipa":"","ex":"Thank you so much for your help today."},
{"word":"you're welcome","zh":"不客气","pos":"phr.","ipa":"","ex":"You're welcome! Let me know if you need anything else."},
{"word":"sorry","zh":"对不起","pos":"interj.","ipa":"","ex":"I'm sorry for being late to the meeting."},
{"word":"excuse me","zh":"打扰一下 / 借过","pos":"phr.","ipa":"","ex":"Excuse me, could you tell me where the restroom is?"},
{"word":"pardon","zh":"请再说一遍","pos":"interj.","ipa":"","ex":"Pardon? I didn't quite catch that."},
{"word":"no problem","zh":"没问题","pos":"phr.","ipa":"","ex":"No problem at all—I'm happy to help."},
{"word":"of course","zh":"当然","pos":"phr.","ipa":"","ex":"Of course! I'll take care of it right away."},
{"word":"sure","zh":"好的 / 当然","pos":"adv.","ipa":"","ex":"Sure, I can meet you at three o'clock."},
{"word":"absolutely","zh":"完全正确 / 绝对","pos":"adv.","ipa":"","ex":"Absolutely! That's a brilliant idea."},
{"word":"maybe","zh":"也许","pos":"adv.","ipa":"","ex":"Maybe we should try the new restaurant nearby."},
{"word":"perhaps","zh":"或许","pos":"adv.","ipa":"","ex":"Perhaps we should reschedule tomorrow's meeting."},
{"word":"I think","zh":"我认为","pos":"phr.","ipa":"","ex":"I think we need more time to finish this project."},
{"word":"I agree","zh":"我同意","pos":"phr.","ipa":"","ex":"I agree with your proposal completely."},
{"word":"I disagree","zh":"我不同意","pos":"phr.","ipa":"","ex":"I disagree—this approach has too many risks."},
{"word":"really","zh":"真的吗 / 真的","pos":"adv.","ipa":"","ex":"Really? I didn't know that at all!"},
{"word":"exactly","zh":"正是 / 确实","pos":"adv.","ipa":"","ex":"Exactly! That's what I've been saying all along."},
{"word":"anyway","zh":"不管怎样","pos":"adv.","ipa":"","ex":"Anyway, let's move on to the next agenda item."},
{"word":"by the way","zh":"顺便说一下","pos":"phr.","ipa":"","ex":"By the way, did you get my email about the deadline?"},
{"word":"actually","zh":"实际上","pos":"adv.","ipa":"","ex":"Actually, I prefer the first option you mentioned."},
{"word":"honestly","zh":"说实话","pos":"adv.","ipa":"","ex":"Honestly, I'm not sure this plan will work."},
{"word":"unfortunately","zh":"不幸的是","pos":"adv.","ipa":"","ex":"Unfortunately, the flight was cancelled due to bad weather."},
{"word":"luckily","zh":"幸运地","pos":"adv.","ipa":"","ex":"Luckily, we found a taxi right away."},
{"word":"obviously","zh":"显然","pos":"adv.","ipa":"","ex":"Obviously, we need a better plan before the launch."},
{"word":"basically","zh":"基本上","pos":"adv.","ipa":"","ex":"Basically, we need to start the whole process over."},
{"word":"generally","zh":"通常 / 一般来说","pos":"adv.","ipa":"","ex":"Generally, the bus arrives every ten minutes."},
{"word":"specifically","zh":"具体地说","pos":"adv.","ipa":"","ex":"Can you be more specific about the project deadline?"},
{"word":"take care","zh":"保重 / 注意","pos":"phr.","ipa":"","ex":"Take care! Stay safe on your trip."},
{"word":"good luck","zh":"祝好运","pos":"phr.","ipa":"","ex":"Good luck with your job interview tomorrow!"},
{"word":"have a nice day","zh":"祝你有美好的一天","pos":"phr.","ipa":"","ex":"Have a nice day! See you next week."},
{"word":"what do you mean","zh":"你什么意思","pos":"phr.","ipa":"","ex":"What do you mean by 'unacceptable results'?"},
{"word":"in other words","zh":"换句话说","pos":"phr.","ipa":"","ex":"In other words, we've completely run out of budget."},
{"word":"for example","zh":"例如","pos":"phr.","ipa":"","ex":"For example, we could use email or a project tool."},
{"word":"however","zh":"然而","pos":"conj.","ipa":"","ex":"The price is high; however, the quality is excellent."},
{"word":"therefore","zh":"因此","pos":"conj.","ipa":"","ex":"The meeting ran late; therefore, we skipped lunch."},
{"word":"furthermore","zh":"此外","pos":"adv.","ipa":"","ex":"Furthermore, the new system saves 30% in operating costs."},
{"word":"in addition","zh":"另外","pos":"phr.","ipa":"","ex":"In addition to English, she speaks French and Spanish."},
{"word":"on the other hand","zh":"另一方面","pos":"phr.","ipa":"","ex":"On the other hand, remote work has many clear advantages."},
{"word":"as a result","zh":"因此 / 结果","pos":"phr.","ipa":"","ex":"As a result, sales increased by 20% this quarter."},
{"word":"in conclusion","zh":"总结来说","pos":"phr.","ipa":"","ex":"In conclusion, I recommend we proceed with option B."},
{"word":"I don't understand","zh":"我不明白","pos":"phr.","ipa":"","ex":"I don't understand. Could you explain that again, please?"},
{"word":"could you repeat that","zh":"能再说一遍吗","pos":"phr.","ipa":"","ex":"Could you repeat that? I missed the last part."},
{"word":"speak slowly please","zh":"请说慢一点","pos":"phr.","ipa":"","ex":"Speak slowly please—English isn't my first language."},
{"word":"I'm not sure","zh":"我不确定","pos":"phr.","ipa":"","ex":"I'm not sure about the exact figures—let me check."},

# ── 2. Daily Life & Household (日常生活) ─────────────────────────────────
{"word":"wake up","zh":"醒来 / 起床","pos":"phr.v.","ipa":"","ex":"I usually wake up at 7 a.m. on weekdays."},
{"word":"get up","zh":"起床","pos":"phr.v.","ipa":"","ex":"It's hard to get up early in winter."},
{"word":"shower","zh":"淋浴","pos":"n./v.","ipa":"","ex":"I take a shower every morning before breakfast."},
{"word":"brush teeth","zh":"刷牙","pos":"phr.","ipa":"","ex":"Don't forget to brush your teeth before bed."},
{"word":"get dressed","zh":"穿衣服","pos":"phr.","ipa":"","ex":"She got dressed quickly and rushed to the morning meeting."},
{"word":"have breakfast","zh":"吃早饭","pos":"phr.","ipa":"","ex":"I always have breakfast before going to work."},
{"word":"cook dinner","zh":"做晚饭","pos":"phr.","ipa":"","ex":"Let's cook dinner at home instead of eating out tonight."},
{"word":"wash dishes","zh":"洗碗","pos":"phr.","ipa":"","ex":"It's your turn to wash dishes tonight."},
{"word":"do laundry","zh":"洗衣服","pos":"phr.","ipa":"","ex":"I do laundry every Sunday afternoon."},
{"word":"vacuum","zh":"用吸尘器打扫","pos":"v.","ipa":"","ex":"Could you vacuum the living room before the guests arrive?"},
{"word":"take out the trash","zh":"倒垃圾","pos":"phr.","ipa":"","ex":"Please take out the trash—the bin is overflowing!"},
{"word":"go to bed","zh":"上床睡觉","pos":"phr.","ipa":"","ex":"The kids should go to bed by nine o'clock."},
{"word":"alarm","zh":"闹钟","pos":"n.","ipa":"","ex":"Set an alarm for 6:30 so we don't oversleep."},
{"word":"fridge","zh":"冰箱","pos":"n.","ipa":"","ex":"There's leftover pizza in the fridge from last night."},
{"word":"microwave","zh":"微波炉","pos":"n.","ipa":"","ex":"Heat the soup in the microwave for two minutes."},
{"word":"oven","zh":"烤箱","pos":"n.","ipa":"","ex":"Preheat the oven to 200 degrees Celsius before baking."},
{"word":"washing machine","zh":"洗衣机","pos":"n.","ipa":"","ex":"The washing machine finished—please hang the clothes out."},
{"word":"bedroom","zh":"卧室","pos":"n.","ipa":"","ex":"The apartment has two bedrooms and one bathroom."},
{"word":"bathroom","zh":"浴室 / 卫生间","pos":"n.","ipa":"","ex":"The bathroom is occupied right now—please wait a moment."},
{"word":"kitchen","zh":"厨房","pos":"n.","ipa":"","ex":"She loves cooking in her spacious, well-equipped kitchen."},
{"word":"living room","zh":"客厅","pos":"n.","ipa":"","ex":"Everyone gathered in the living room to watch the game."},
{"word":"neighbor","zh":"邻居","pos":"n.","ipa":"","ex":"Our neighbors are very friendly and always say hello."},
{"word":"apartment","zh":"公寓","pos":"n.","ipa":"","ex":"I'm looking for a two-bedroom apartment near downtown."},
{"word":"rent","zh":"租金 / 租","pos":"n./v.","ipa":"","ex":"The monthly rent is 8,000 yuan, utilities not included."},
{"word":"landlord","zh":"房东","pos":"n.","ipa":"","ex":"My landlord fixed the broken heater within 24 hours."},
{"word":"lease","zh":"租约","pos":"n.","ipa":"","ex":"Please read the lease carefully before you sign it."},
{"word":"furniture","zh":"家具","pos":"n.","ipa":"","ex":"The apartment comes fully furnished with brand-new furniture."},
{"word":"grocery store","zh":"超市 / 杂货店","pos":"n.","ipa":"","ex":"I'm heading to the grocery store—do you need anything?"},
{"word":"receipt","zh":"收据","pos":"n.","ipa":"","ex":"Keep the receipt in case you need to return the item."},
{"word":"cash","zh":"现金","pos":"n.","ipa":"","ex":"Some small shops only accept cash, not cards."},
{"word":"credit card","zh":"信用卡","pos":"n.","ipa":"","ex":"I'll pay with my credit card to earn reward points."},
{"word":"electricity bill","zh":"电费账单","pos":"n.","ipa":"","ex":"The electricity bill went up because of the air conditioning."},
{"word":"utility","zh":"水电费等公用费","pos":"n.","ipa":"","ex":"Utilities are included in the monthly rent price."},
{"word":"neighborhood","zh":"小区 / 街区","pos":"n.","ipa":"","ex":"This is a quiet neighborhood close to excellent schools."},
{"word":"elevator","zh":"电梯","pos":"n.","ipa":"","ex":"The elevator is out of order—we'll have to take the stairs."},
{"word":"parking lot","zh":"停车场","pos":"n.","ipa":"","ex":"The parking lot is full—let's try parking on the street."},
{"word":"mailbox","zh":"邮箱 / 信箱","pos":"n.","ipa":"","ex":"Check the mailbox—I'm expecting an important package."},
{"word":"package","zh":"包裹","pos":"n.","ipa":"","ex":"A package arrived for you while you were out."},
{"word":"roommate","zh":"室友","pos":"n.","ipa":"","ex":"My roommate and I take turns cooking dinner each week."},
{"word":"chores","zh":"家务活","pos":"n.","ipa":"","ex":"We split the household chores evenly between the two of us."},
{"word":"routine","zh":"日常习惯","pos":"n.","ipa":"","ex":"A healthy morning routine sets a positive tone for the day."},
{"word":"commute","zh":"通勤","pos":"n./v.","ipa":"","ex":"My commute to the office takes about 40 minutes by subway."},
{"word":"move in","zh":"搬入","pos":"phr.v.","ipa":"","ex":"We plan to move in to the new apartment next month."},
{"word":"deposit","zh":"押金 / 定金","pos":"n.","ipa":"","ex":"We paid two months' rent as a security deposit."},
{"word":"repair","zh":"修理","pos":"v./n.","ipa":"","ex":"The plumber came to repair the leaking pipe under the sink."},
{"word":"air conditioner","zh":"空调","pos":"n.","ipa":"","ex":"It's 35 degrees outside—please turn on the air conditioner."},
{"word":"heater","zh":"暖气 / 取暖器","pos":"n.","ipa":"","ex":"The heater broke down right in the middle of winter."},
{"word":"Wi-Fi password","zh":"无线网络密码","pos":"n.","ipa":"","ex":"What's the Wi-Fi password? I need to get online for work."},
{"word":"delivery","zh":"外卖 / 快递","pos":"n.","ipa":"","ex":"I ordered food delivery since there's nothing in the fridge."},
{"word":"recycling","zh":"回收","pos":"n.","ipa":"","ex":"Put the plastic bottles in the recycling bin by the door."},
{"word":"tidy up","zh":"整理 / 收拾","pos":"phr.v.","ipa":"","ex":"Let's tidy up the apartment before the guests arrive tonight."},
{"word":"broken","zh":"坏掉的","pos":"adj.","ipa":"","ex":"The handle of the drawer is broken—be careful."},
{"word":"grocery list","zh":"购物清单","pos":"n.","ipa":"","ex":"I made a grocery list so we don't forget anything at the store."},
{"word":"leftovers","zh":"剩菜 / 剩饭","pos":"n.","ipa":"","ex":"I had yesterday's leftovers for lunch to avoid waste."},
{"word":"expiry date","zh":"有效期 / 保质期","pos":"n.","ipa":"","ex":"Always check the expiry date before eating that yogurt."},
{"word":"smoke detector","zh":"烟雾探测器","pos":"n.","ipa":"","ex":"Test the smoke detector batteries every six months."},
{"word":"first aid kit","zh":"急救箱","pos":"n.","ipa":"","ex":"Keep a first aid kit in an easily accessible location at home."},
{"word":"storage","zh":"储物空间","pos":"n.","ipa":"","ex":"Extra storage boxes are kept in the basement of the building."},
{"word":"furnished","zh":"附带家具的","pos":"adj.","ipa":"","ex":"Is the apartment furnished or do we need to buy everything?"},
{"word":"pet-friendly","zh":"允许养宠物的","pos":"adj.","ipa":"","ex":"We chose a pet-friendly apartment for our two cats."},

# ── 3. Work & Office (工作职场) ──────────────────────────────────────────
{"word":"colleague","zh":"同事","pos":"n.","ipa":"","ex":"My colleague helped me finish the report before the deadline."},
{"word":"boss","zh":"老板 / 上司","pos":"n.","ipa":"","ex":"My boss approved the new project budget this morning."},
{"word":"manager","zh":"经理","pos":"n.","ipa":"","ex":"Please send the proposal directly to the project manager."},
{"word":"employee","zh":"员工","pos":"n.","ipa":"","ex":"The company has over 500 employees across three offices."},
{"word":"team","zh":"团队","pos":"n.","ipa":"","ex":"Our team meets every Monday morning to review the week's goals."},
{"word":"department","zh":"部门","pos":"n.","ipa":"","ex":"The HR department handles all new employee onboarding."},
{"word":"deadline","zh":"截止日期","pos":"n.","ipa":"","ex":"The deadline for this report is end of day Friday."},
{"word":"project","zh":"项目","pos":"n.","ipa":"","ex":"This project is due next month, so we need to stay on track."},
{"word":"task","zh":"任务","pos":"n.","ipa":"","ex":"Please assign each team member a specific task by tomorrow."},
{"word":"report","zh":"报告","pos":"n.","ipa":"","ex":"I need to submit the monthly sales report by noon today."},
{"word":"presentation","zh":"演示 / 汇报","pos":"n.","ipa":"","ex":"She gave an excellent presentation to the board of directors."},
{"word":"email","zh":"电子邮件","pos":"n.","ipa":"","ex":"I'll send you the contract via email this afternoon."},
{"word":"meeting","zh":"会议","pos":"n.","ipa":"","ex":"The team meeting is scheduled for 10 a.m. in Room B."},
{"word":"appointment","zh":"预约 / 约会","pos":"n.","ipa":"","ex":"I have a dentist appointment at two o'clock tomorrow."},
{"word":"salary","zh":"薪资","pos":"n.","ipa":"","ex":"He negotiated a higher salary when he changed companies."},
{"word":"raise","zh":"加薪","pos":"n.","ipa":"","ex":"She asked her manager for a raise after three years in the role."},
{"word":"bonus","zh":"奖金","pos":"n.","ipa":"","ex":"Everyone on the team received a performance bonus this year."},
{"word":"overtime","zh":"加班","pos":"n.","ipa":"","ex":"We had to work overtime to meet the client's tight deadline."},
{"word":"remote work","zh":"远程工作","pos":"n.","ipa":"","ex":"Remote work has become standard practice in many tech companies."},
{"word":"home office","zh":"家庭办公室","pos":"n.","ipa":"","ex":"I set up a proper home office with a standing desk and monitor."},
{"word":"laptop","zh":"笔记本电脑","pos":"n.","ipa":"","ex":"I carry my laptop everywhere so I can work from anywhere."},
{"word":"conference room","zh":"会议室","pos":"n.","ipa":"","ex":"The conference room is booked from 2 to 4 this afternoon."},
{"word":"agenda","zh":"议程","pos":"n.","ipa":"","ex":"Can you send the meeting agenda at least an hour in advance?"},
{"word":"minutes","zh":"会议记录","pos":"n.","ipa":"","ex":"Could you take the minutes of today's meeting, please?"},
{"word":"feedback","zh":"反馈","pos":"n.","ipa":"","ex":"Please give me feedback on this draft before I send it out."},
{"word":"performance review","zh":"绩效评估","pos":"n.","ipa":"","ex":"Annual performance reviews are held every December here."},
{"word":"goal","zh":"目标","pos":"n.","ipa":"","ex":"Set clear and measurable goals at the start of each quarter."},
{"word":"strategy","zh":"策略","pos":"n.","ipa":"","ex":"We need a new marketing strategy to reach younger customers."},
{"word":"proposal","zh":"提案 / 方案","pos":"n.","ipa":"","ex":"The team submitted a detailed proposal to the client yesterday."},
{"word":"contract","zh":"合同","pos":"n.","ipa":"","ex":"Please review the contract carefully before you sign it."},
{"word":"client","zh":"客户","pos":"n.","ipa":"","ex":"We have a very important client meeting scheduled for Friday."},
{"word":"budget","zh":"预算","pos":"n.","ipa":"","ex":"The marketing budget for this quarter has already been used up."},
{"word":"invoice","zh":"发票","pos":"n.","ipa":"","ex":"Please send the invoice to the accounts payable department."},
{"word":"expense","zh":"费用 / 开支","pos":"n.","ipa":"","ex":"Submit all your travel expenses within 30 days of the trip."},
{"word":"reimbursement","zh":"报销","pos":"n.","ipa":"","ex":"Apply for reimbursement by filling in the expense claim form."},
{"word":"hire","zh":"雇佣","pos":"v.","ipa":"","ex":"We plan to hire three new developers in the next quarter."},
{"word":"resign","zh":"辞职","pos":"v.","ipa":"","ex":"She decided to resign after receiving a better offer abroad."},
{"word":"promote","zh":"晋升","pos":"v.","ipa":"","ex":"He was promoted to senior manager after two years of hard work."},
{"word":"intern","zh":"实习生","pos":"n.","ipa":"","ex":"We have two interns joining the design team this summer."},
{"word":"job interview","zh":"工作面试","pos":"n.","ipa":"","ex":"I have a job interview at Google next Tuesday afternoon."},
{"word":"resume","zh":"简历","pos":"n.","ipa":"","ex":"Update your resume before applying for the position."},
{"word":"cover letter","zh":"求职信","pos":"n.","ipa":"","ex":"A well-written cover letter can make your application stand out."},
{"word":"probation","zh":"试用期","pos":"n.","ipa":"","ex":"New employees complete a three-month probation period here."},
{"word":"workload","zh":"工作量","pos":"n.","ipa":"","ex":"My workload this month is much heavier than usual."},
{"word":"priority","zh":"优先级","pos":"n.","ipa":"","ex":"Let's discuss which tasks should be our top priorities today."},
{"word":"urgent","zh":"紧急的","pos":"adj.","ipa":"","ex":"This is urgent—please respond to the client within the hour."},
{"word":"collaborate","zh":"合作","pos":"v.","ipa":"","ex":"The two departments will collaborate closely on this product launch."},
{"word":"productive","zh":"高效的","pos":"adj.","ipa":"","ex":"We had a very productive brainstorming session this morning."},
{"word":"professional","zh":"专业的","pos":"adj.","ipa":"","ex":"Always maintain a professional tone in client communications."},
{"word":"HR","zh":"人力资源部","pos":"n.","ipa":"","ex":"Contact HR if you have questions about your employment contract."},
{"word":"annual leave","zh":"年假","pos":"n.","ipa":"","ex":"I'm planning to use my annual leave for a trip to Europe."},
{"word":"sick leave","zh":"病假","pos":"n.","ipa":"","ex":"She called in sick and applied for two days of sick leave."},
{"word":"benefits","zh":"福利","pos":"n.","ipa":"","ex":"The company offers excellent benefits including health and dental."},
{"word":"full-time","zh":"全职","pos":"adj.","ipa":"","ex":"I'm looking for a full-time position in software development."},
{"word":"part-time","zh":"兼职","pos":"adj.","ipa":"","ex":"She works part-time while finishing her master's degree."},
{"word":"freelance","zh":"自由职业","pos":"adj./n.","ipa":"","ex":"He works as a freelance designer for several tech startups."},
{"word":"business card","zh":"名片","pos":"n.","ipa":"","ex":"Please exchange business cards with the clients after the lunch."},
{"word":"networking","zh":"建立人脉","pos":"n.","ipa":"","ex":"Industry conferences are great for networking with peers."},
{"word":"training","zh":"培训","pos":"n.","ipa":"","ex":"New hires attend a one-week training programme before starting."},
{"word":"onboarding","zh":"入职培训","pos":"n.","ipa":"","ex":"The onboarding process includes a tour and introductions to all teams."},
{"word":"handover","zh":"工作交接","pos":"n.","ipa":"","ex":"Please prepare a detailed handover document before your last day."},
{"word":"delegate","zh":"委派 / 授权","pos":"v.","ipa":"","ex":"A good manager knows how to delegate tasks effectively."},

# ── 4. Business Meetings (商务会议) ──────────────────────────────────────
{"word":"attendee","zh":"参会者","pos":"n.","ipa":"","ex":"Please confirm the list of attendees before sending invitations."},
{"word":"chairperson","zh":"主持人 / 主席","pos":"n.","ipa":"","ex":"The chairperson opened the meeting and reviewed the agenda."},
{"word":"presenter","zh":"演讲者","pos":"n.","ipa":"","ex":"Each presenter has 15 minutes to deliver their quarterly update."},
{"word":"video conference","zh":"视频会议","pos":"n.","ipa":"","ex":"We hold a weekly video conference with our overseas team."},
{"word":"mute","zh":"静音","pos":"v./adj.","ipa":"","ex":"Please mute yourself when you're not speaking in the call."},
{"word":"screen share","zh":"屏幕共享","pos":"n.","ipa":"","ex":"Can you screen share so everyone can see the presentation?"},
{"word":"action item","zh":"待办事项","pos":"n.","ipa":"","ex":"Let's assign an action item to each team member before we close."},
{"word":"takeaway","zh":"主要结论","pos":"n.","ipa":"","ex":"The key takeaway from today's meeting is that we need more data."},
{"word":"deliverable","zh":"可交付成果","pos":"n.","ipa":"","ex":"List all deliverables and their due dates in the project plan."},
{"word":"KPI","zh":"关键绩效指标 / Key Performance Indicator","pos":"n.","ipa":"","ex":"Each department tracks its own set of KPIs every quarter."},
{"word":"milestone","zh":"里程碑","pos":"n.","ipa":"","ex":"Hitting the first million users is a major milestone for us."},
{"word":"quarterly","zh":"季度的","pos":"adj.","ipa":"","ex":"We hold quarterly reviews to assess overall business performance."},
{"word":"fiscal year","zh":"财年","pos":"n.","ipa":"","ex":"Our fiscal year runs from April to March."},
{"word":"revenue","zh":"营收","pos":"n.","ipa":"","ex":"Revenue grew by 35% compared to the same period last year."},
{"word":"profit","zh":"利润","pos":"n.","ipa":"","ex":"The company returned to profit after two difficult quarters."},
{"word":"ROI","zh":"投资回报率 / Return on Investment","pos":"n.","ipa":"","ex":"The campaign delivered an impressive ROI of over 200%."},
{"word":"market share","zh":"市场份额","pos":"n.","ipa":"","ex":"We aim to grow our market share to 20% within two years."},
{"word":"forecast","zh":"预测","pos":"n./v.","ipa":"","ex":"The sales forecast for next quarter looks very promising."},
{"word":"negotiation","zh":"谈判","pos":"n.","ipa":"","ex":"Price negotiation with the supplier took three rounds of talks."},
{"word":"terms and conditions","zh":"条款与条件","pos":"n.","ipa":"","ex":"Please read the terms and conditions before signing the agreement."},
{"word":"discount","zh":"折扣","pos":"n.","ipa":"","ex":"We can offer a 10% discount for orders above 1,000 units."},
{"word":"close a deal","zh":"成交","pos":"phr.","ipa":"","ex":"We finally closed the deal after three months of negotiation."},
{"word":"approve","zh":"批准","pos":"v.","ipa":"","ex":"The board approved the new investment plan unanimously."},
{"word":"postpone","zh":"推迟","pos":"v.","ipa":"","ex":"We had to postpone the product launch due to supply chain issues."},
{"word":"reschedule","zh":"重新安排","pos":"v.","ipa":"","ex":"Can we reschedule Friday's meeting to the following Monday?"},
{"word":"wrap up","zh":"总结 / 结束","pos":"phr.v.","ipa":"","ex":"Let's wrap up—we only have five minutes left in this meeting."},
{"word":"follow up","zh":"跟进","pos":"phr.v./n.","ipa":"","ex":"I'll follow up with the client after they review the proposal."},
{"word":"action plan","zh":"行动计划","pos":"n.","ipa":"","ex":"We need a clear action plan before the end of this meeting."},
{"word":"stakeholder","zh":"利益相关方","pos":"n.","ipa":"","ex":"All key stakeholders must be informed before any major decision."},
{"word":"heads up","zh":"提前告知","pos":"n./phr.","ipa":"","ex":"Just a heads up—the client may ask about pricing tomorrow."},
{"word":"bottom line","zh":"底线 / 净利润","pos":"n.","ipa":"","ex":"The bottom line is that we can't afford to delay any further."},
{"word":"loop in","zh":"将某人加入沟通","pos":"phr.v.","ipa":"","ex":"Please loop in the legal team before we finalize the contract."},
{"word":"off the record","zh":"私下里 / 非正式地","pos":"phr.","ipa":"","ex":"Off the record, I think the merger is very unlikely to happen."},
{"word":"due diligence","zh":"尽职调查","pos":"n.","ipa":"","ex":"We performed full due diligence before acquiring the startup."},
{"word":"benchmark","zh":"基准 / 对标","pos":"n.","ipa":"","ex":"Let's benchmark our performance against industry standards."},

# ── 5. Travel (旅行) ─────────────────────────────────────────────────────
{"word":"passport","zh":"护照","pos":"n.","ipa":"","ex":"Make sure your passport is valid for at least six more months."},
{"word":"visa","zh":"签证","pos":"n.","ipa":"","ex":"I need to apply for a Schengen visa before I travel to Europe."},
{"word":"ticket","zh":"票 / 门票","pos":"n.","ipa":"","ex":"I booked my train tickets online two weeks in advance."},
{"word":"flight","zh":"航班","pos":"n.","ipa":"","ex":"My flight departs at 8 a.m., so I need to leave home by 5:30."},
{"word":"airline","zh":"航空公司","pos":"n.","ipa":"","ex":"Which airline do you usually fly when travelling to Europe?"},
{"word":"airport","zh":"机场","pos":"n.","ipa":"","ex":"We should arrive at the airport at least two hours early."},
{"word":"check in","zh":"值机 / 办理入住","pos":"phr.v.","ipa":"","ex":"You can check in online up to 24 hours before departure."},
{"word":"boarding pass","zh":"登机牌","pos":"n.","ipa":"","ex":"Please have your boarding pass ready to show at the gate."},
{"word":"gate","zh":"登机口","pos":"n.","ipa":"","ex":"Our flight departs from Gate 27 at the far end of Terminal 2."},
{"word":"departure","zh":"出发 / 离港","pos":"n.","ipa":"","ex":"Check the departure board for your gate number and time."},
{"word":"arrival","zh":"到达 / 到港","pos":"n.","ipa":"","ex":"The arrival time has been changed to 11:30 p.m. due to a delay."},
{"word":"delay","zh":"延误","pos":"n./v.","ipa":"","ex":"The flight was delayed by two hours because of bad weather."},
{"word":"cancel","zh":"取消","pos":"v.","ipa":"","ex":"The airline cancelled the flight and rebooked all passengers."},
{"word":"baggage","zh":"行李","pos":"n.","ipa":"","ex":"Each passenger is allowed one piece of checked baggage up to 23 kg."},
{"word":"carry-on","zh":"随身行李","pos":"n.","ipa":"","ex":"My carry-on bag fits perfectly in the overhead bin."},
{"word":"customs","zh":"海关","pos":"n.","ipa":"","ex":"You must declare any goods over the duty-free limit at customs."},
{"word":"declaration","zh":"申报","pos":"n.","ipa":"","ex":"Fill in the customs declaration form before landing."},
{"word":"immigration","zh":"入境检查 / 移民局","pos":"n.","ipa":"","ex":"The immigration queue at the airport was almost two hours long."},
{"word":"hotel","zh":"酒店","pos":"n.","ipa":"","ex":"I booked a hotel near the city centre for three nights."},
{"word":"hostel","zh":"青旅 / 青年旅舍","pos":"n.","ipa":"","ex":"Staying in a hostel is a great way to meet fellow travellers."},
{"word":"reservation","zh":"预订","pos":"n.","ipa":"","ex":"I made a reservation for two at the restaurant for 7 p.m."},
{"word":"check out","zh":"退房 / 结账","pos":"phr.v.","ipa":"","ex":"Check-out time is 11 a.m.—please leave your key at the front desk."},
{"word":"room service","zh":"客房服务","pos":"n.","ipa":"","ex":"I ordered breakfast via room service so I didn't have to go down."},
{"word":"front desk","zh":"前台 / 接待台","pos":"n.","ipa":"","ex":"Please call the front desk if you need extra towels or pillows."},
{"word":"tour guide","zh":"导游","pos":"n.","ipa":"","ex":"Our tour guide spoke excellent English and knew everything about the city."},
{"word":"sightseeing","zh":"观光","pos":"n.","ipa":"","ex":"We spent the whole afternoon sightseeing around the Old Town."},
{"word":"landmark","zh":"地标","pos":"n.","ipa":"","ex":"The Eiffel Tower is the most famous landmark in Paris."},
{"word":"museum","zh":"博物馆","pos":"n.","ipa":"","ex":"The British Museum is free to enter and open every day."},
{"word":"attraction","zh":"景点","pos":"n.","ipa":"","ex":"The city has dozens of top tourist attractions worth visiting."},
{"word":"map","zh":"地图","pos":"n.","ipa":"","ex":"Download an offline map before you travel to save mobile data."},
{"word":"taxi","zh":"出租车","pos":"n.","ipa":"","ex":"Let's grab a taxi—it's too far to walk with all this luggage."},
{"word":"subway","zh":"地铁","pos":"n.","ipa":"","ex":"Taking the subway is the fastest way to get across the city."},
{"word":"rent a car","zh":"租车","pos":"phr.","ipa":"","ex":"We decided to rent a car so we could explore the countryside."},
{"word":"toll","zh":"过路费","pos":"n.","ipa":"","ex":"Keep some cash handy for the highway toll booths."},
{"word":"traffic jam","zh":"交通堵塞","pos":"n.","ipa":"","ex":"We were stuck in a traffic jam for over an hour on the motorway."},
{"word":"lost","zh":"迷路的","pos":"adj.","ipa":"","ex":"We got completely lost in the old part of the city."},
{"word":"direction","zh":"方向","pos":"n.","ipa":"","ex":"Excuse me, could you give me directions to the train station?"},
{"word":"turn left","zh":"左转","pos":"phr.","ipa":"","ex":"Turn left at the traffic lights and walk for about 200 metres."},
{"word":"turn right","zh":"右转","pos":"phr.","ipa":"","ex":"Turn right after the pharmacy and the hotel is on your left."},
{"word":"straight ahead","zh":"直走","pos":"phr.","ipa":"","ex":"Go straight ahead for two blocks and you'll see the entrance."},
{"word":"round trip","zh":"往返","pos":"n.","ipa":"","ex":"A round-trip ticket to Tokyo costs about USD 800."},
{"word":"one way","zh":"单程","pos":"n.","ipa":"","ex":"I only need a one-way ticket since I'm coming back by train."},
{"word":"economy class","zh":"经济舱","pos":"n.","ipa":"","ex":"Economy class tickets are much cheaper if booked in advance."},
{"word":"business class","zh":"商务舱","pos":"n.","ipa":"","ex":"The company paid for a business class seat on the long-haul flight."},
{"word":"window seat","zh":"靠窗座位","pos":"n.","ipa":"","ex":"I always request a window seat so I can see the view below."},
{"word":"aisle seat","zh":"靠走道座位","pos":"n.","ipa":"","ex":"She prefers an aisle seat so she can stretch her legs easily."},
{"word":"turbulence","zh":"气流颤动","pos":"n.","ipa":"","ex":"The pilot asked everyone to fasten seatbelts due to turbulence."},
{"word":"jet lag","zh":"时差反应","pos":"n.","ipa":"","ex":"I suffered from terrible jet lag after the 12-hour flight."},
{"word":"time zone","zh":"时区","pos":"n.","ipa":"","ex":"London and Beijing are 8 hours apart in time zones."},
{"word":"exchange rate","zh":"汇率","pos":"n.","ipa":"","ex":"Check the exchange rate before converting your money at the airport."},
{"word":"tip","zh":"小费","pos":"n./v.","ipa":"","ex":"It is customary to tip around 15-20% at restaurants in the US."},
{"word":"souvenir","zh":"纪念品","pos":"n.","ipa":"","ex":"I bought some local souvenirs for my family back home."},
{"word":"itinerary","zh":"行程安排","pos":"n.","ipa":"","ex":"Please email me the full itinerary at least a week before we go."},
{"word":"travel insurance","zh":"旅行保险","pos":"n.","ipa":"","ex":"Always buy travel insurance before going on a long international trip."},
{"word":"suitcase","zh":"行李箱","pos":"n.","ipa":"","ex":"My suitcase was overweight—I had to remove two books."},
{"word":"backpack","zh":"背包","pos":"n.","ipa":"","ex":"Backpackers usually carry everything they need in one large backpack."},
{"word":"layover","zh":"中途转机停留","pos":"n.","ipa":"","ex":"We have a four-hour layover in Dubai before the connecting flight."},
{"word":"transit","zh":"中转","pos":"n.","ipa":"","ex":"I'm on a transit visa and cannot leave the international terminal."},
{"word":"baggage claim","zh":"行李领取处","pos":"n.","ipa":"","ex":"Meet me at the baggage claim area after you clear immigration."},
{"word":"lost luggage","zh":"行李丢失","pos":"phr.","ipa":"","ex":"Report lost luggage to the airline counter before you leave the airport."},
{"word":"do not disturb","zh":"请勿打扰","pos":"phr.","ipa":"","ex":"I hung the do-not-disturb sign on the door so I could sleep in."},
{"word":"housekeeping","zh":"客房打扫服务","pos":"n.","ipa":"","ex":"I asked housekeeping to bring extra towels and a hair dryer."},
{"word":"complimentary","zh":"免费赠送的","pos":"adj.","ipa":"","ex":"Breakfast is complimentary for guests staying three nights or more."},
{"word":"late checkout","zh":"延迟退房","pos":"n.","ipa":"","ex":"Can I request a late checkout until 2 p.m. for an extra fee?"},
{"word":"peak season","zh":"旺季","pos":"n.","ipa":"","ex":"Flights are much more expensive during the peak summer season."},
{"word":"off season","zh":"淡季","pos":"n.","ipa":"","ex":"Travelling in the off season saves money and means fewer crowds."},
{"word":"local SIM card","zh":"当地SIM卡","pos":"n.","ipa":"","ex":"Buy a local SIM card at the airport for cheaper data and calls."},
{"word":"power bank","zh":"移动电源","pos":"n.","ipa":"","ex":"Always carry a power bank when you travel—outlets can be hard to find."},
{"word":"security check","zh":"安全检查","pos":"n.","ipa":"","ex":"You must remove your laptop from the bag at the security check."},
{"word":"boarding time","zh":"登机时间","pos":"n.","ipa":"","ex":"Boarding time is 7:15 a.m.—don't be late!"},
{"word":"check-in counter","zh":"值机柜台","pos":"n.","ipa":"","ex":"Go to the check-in counter to drop your bags and get your pass."},
{"word":"all-inclusive","zh":"全包价","pos":"adj.","ipa":"","ex":"We chose an all-inclusive resort so we didn't have to worry about costs."},

# ── 6. Visa Application (签证办理) ───────────────────────────────────────
{"word":"application form","zh":"申请表","pos":"n.","ipa":"","ex":"Fill in the application form clearly and accurately in block letters."},
{"word":"fill out","zh":"填写","pos":"phr.v.","ipa":"","ex":"Please fill out the form completely before submitting it."},
{"word":"submit","zh":"提交","pos":"v.","ipa":"","ex":"Submit your application at least four weeks before your travel date."},
{"word":"embassy","zh":"大使馆","pos":"n.","ipa":"","ex":"I have an appointment at the French Embassy next Wednesday."},
{"word":"consulate","zh":"领事馆","pos":"n.","ipa":"","ex":"Visa applications can be submitted at the nearest consulate."},
{"word":"invitation letter","zh":"邀请函","pos":"n.","ipa":"","ex":"My friend sent me an official invitation letter for the visa."},
{"word":"bank statement","zh":"银行流水 / 对账单","pos":"n.","ipa":"","ex":"Provide three months of bank statements to prove financial stability."},
{"word":"proof of income","zh":"收入证明","pos":"n.","ipa":"","ex":"A letter from your employer can serve as proof of income."},
{"word":"employment letter","zh":"在职证明","pos":"n.","ipa":"","ex":"Your employer must provide an employment letter on official letterhead."},
{"word":"accommodation proof","zh":"住宿证明","pos":"n.","ipa":"","ex":"A hotel booking confirmation counts as valid accommodation proof."},
{"word":"validity","zh":"有效期","pos":"n.","ipa":"","ex":"Your passport must have a validity of at least six months."},
{"word":"single entry","zh":"单次入境","pos":"n.","ipa":"","ex":"A single-entry visa allows you to enter the country only once."},
{"word":"multiple entry","zh":"多次入境","pos":"n.","ipa":"","ex":"A multiple-entry visa is more convenient for frequent business travellers."},
{"word":"tourist visa","zh":"旅游签证","pos":"n.","ipa":"","ex":"Apply for a tourist visa if you're visiting purely for leisure."},
{"word":"business visa","zh":"商务签证","pos":"n.","ipa":"","ex":"A business visa is required for attending trade conferences abroad."},
{"word":"student visa","zh":"学生签证","pos":"n.","ipa":"","ex":"She received her student visa four weeks after applying online."},
{"word":"transit visa","zh":"过境签证","pos":"n.","ipa":"","ex":"Some nationalities need a transit visa even for a short layover."},
{"word":"rejection","zh":"拒签","pos":"n.","ipa":"","ex":"After the rejection, she reapplied with more supporting documents."},
{"word":"appeal","zh":"申诉","pos":"n./v.","ipa":"","ex":"You have the right to appeal if your visa application is refused."},
{"word":"processing time","zh":"审理时间","pos":"n.","ipa":"","ex":"The standard processing time for this visa is ten working days."},
{"word":"biometrics","zh":"生物特征采集","pos":"n.","ipa":"","ex":"Attend your biometrics appointment to provide fingerprints and a photo."},
{"word":"fingerprint","zh":"指纹","pos":"n.","ipa":"","ex":"You will be asked to scan all ten fingerprints at the visa centre."},
{"word":"notarization","zh":"公证","pos":"n.","ipa":"","ex":"Documents in Chinese require notarization and official translation."},
{"word":"certified copy","zh":"经认证副本","pos":"n.","ipa":"","ex":"Submit certified copies of your birth certificate and marriage licence."},
{"word":"reference number","zh":"参考编号","pos":"n.","ipa":"","ex":"Quote your reference number when enquiring about your application."},
{"word":"duration of stay","zh":"停留时长","pos":"n.","ipa":"","ex":"The visa permits a maximum duration of stay of 90 days."},
{"word":"purpose of visit","zh":"访问目的","pos":"n.","ipa":"","ex":"State your purpose of visit clearly on the application form."},
{"word":"overstay","zh":"超期逗留","pos":"v./n.","ipa":"","ex":"Overstaying your visa can result in a ban from re-entering the country."},
{"word":"residence permit","zh":"居留许可","pos":"n.","ipa":"","ex":"After living there for a year, she applied for a residence permit."},
{"word":"extension","zh":"续签 / 延期","pos":"n.","ipa":"","ex":"She applied for a visa extension before her original one expired."},
{"word":"point of entry","zh":"入境口岸","pos":"n.","ipa":"","ex":"Declare your point of entry clearly on the arrival card."},
{"word":"sponsor","zh":"担保人","pos":"n.","ipa":"","ex":"The company acted as a sponsor for the employee's work visa."},
{"word":"self-employed","zh":"自雇","pos":"adj.","ipa":"","ex":"Self-employed applicants must submit tax records as income proof."},

# ── 7. Restaurant & Ordering (点餐饮食) ──────────────────────────────────
{"word":"menu","zh":"菜单","pos":"n.","ipa":"","ex":"Could we see the menu, please? We're ready to order."},
{"word":"order","zh":"点餐 / 订单","pos":"n./v.","ipa":"","ex":"Are you ready to order, or do you need a few more minutes?"},
{"word":"appetizer","zh":"开胃菜","pos":"n.","ipa":"","ex":"We shared a soup and salad as appetizers before the main course."},
{"word":"main course","zh":"主菜","pos":"n.","ipa":"","ex":"For the main course, I'll have the grilled salmon, please."},
{"word":"dessert","zh":"甜点","pos":"n.","ipa":"","ex":"I'm too full for dessert—maybe just a coffee."},
{"word":"side dish","zh":"配菜","pos":"n.","ipa":"","ex":"Would you like to choose a side dish to go with your steak?"},
{"word":"beverage","zh":"饮料","pos":"n.","ipa":"","ex":"What beverages are available? I'd like something non-alcoholic."},
{"word":"sparkling water","zh":"气泡水","pos":"n.","ipa":"","ex":"Still or sparkling water for the table tonight?"},
{"word":"coffee","zh":"咖啡","pos":"n.","ipa":"","ex":"I'll have a flat white coffee with oat milk, please."},
{"word":"vegetarian","zh":"素食的 / 素食者","pos":"adj./n.","ipa":"","ex":"Do you have any vegetarian options on the menu today?"},
{"word":"vegan","zh":"纯素食的 / 纯素食者","pos":"adj./n.","ipa":"","ex":"She is vegan, so she avoids all animal products including dairy."},
{"word":"gluten-free","zh":"无麸质的","pos":"adj.","ipa":"","ex":"Is this dish gluten-free? I have a wheat intolerance."},
{"word":"allergen","zh":"过敏原","pos":"n.","ipa":"","ex":"Please check for nut allergens—my son has a severe nut allergy."},
{"word":"spicy","zh":"辣的","pos":"adj.","ipa":"","ex":"How spicy is this dish? I can only handle mild heat."},
{"word":"well done","zh":"全熟的","pos":"adj.","ipa":"","ex":"I'd like my steak well done, no pink at all please."},
{"word":"medium","zh":"五分熟的","pos":"adj.","ipa":"","ex":"Could I have the burger cooked medium with a little pink inside?"},
{"word":"rare","zh":"三分熟的","pos":"adj.","ipa":"","ex":"He prefers his beef rare—just seared on the outside."},
{"word":"portion","zh":"份量","pos":"n.","ipa":"","ex":"The portions here are enormous—we could easily share one dish."},
{"word":"takeaway","zh":"外卖 / 打包","pos":"n.","ipa":"","ex":"Is this for dining in or takeaway? I'll pack it for you if needed."},
{"word":"delivery","zh":"外送","pos":"n.","ipa":"","ex":"Delivery usually takes around 30 minutes from this restaurant."},
{"word":"dine in","zh":"堂食","pos":"phr.","ipa":"","ex":"I prefer to dine in rather than eat at my desk every day."},
{"word":"table for two","zh":"两人桌","pos":"phr.","ipa":"","ex":"Good evening—do you have a table for two available tonight?"},
{"word":"waiter","zh":"服务员","pos":"n.","ipa":"","ex":"Excuse me, waiter—could we have the bill when you're ready?"},
{"word":"bill","zh":"账单","pos":"n.","ipa":"","ex":"Could we have the bill, please? We're in a bit of a hurry."},
{"word":"split the bill","zh":"AA制 / 分摊账单","pos":"phr.","ipa":"","ex":"Shall we split the bill equally or pay for our own orders?"},
{"word":"treat","zh":"请客","pos":"v./n.","ipa":"","ex":"I'll treat you to lunch today—it's your birthday after all!"},
{"word":"recommendation","zh":"推荐","pos":"n.","ipa":"","ex":"What's your recommendation? I've never been here before."},
{"word":"daily special","zh":"今日特供","pos":"n.","ipa":"","ex":"The daily special is roast duck with seasonal vegetables today."},
{"word":"set meal","zh":"套餐","pos":"n.","ipa":"","ex":"The set meal includes a starter, main course, and a soft drink."},
{"word":"buffet","zh":"自助餐","pos":"n.","ipa":"","ex":"The hotel serves an all-you-can-eat breakfast buffet every morning."},
{"word":"reservation","zh":"预订 / 预约","pos":"n.","ipa":"","ex":"I have a reservation under the name Johnson for 7 p.m."},
{"word":"waiting list","zh":"候位名单","pos":"n.","ipa":"","ex":"We're fully booked, but I can put you on the waiting list."},
{"word":"outdoor seating","zh":"户外座位","pos":"n.","ipa":"","ex":"Could we have a table in the outdoor seating area? The weather's lovely."},
{"word":"non-smoking","zh":"无烟区","pos":"adj.","ipa":"","ex":"We'd prefer a table in the non-smoking section, please."},
{"word":"refill","zh":"续杯","pos":"n./v.","ipa":"","ex":"May I have a refill on the iced tea? It's very refreshing."},
{"word":"to go","zh":"打包带走","pos":"phr.","ipa":"","ex":"Could you box up the rest of my pasta to go, please?"},
{"word":"sauce","zh":"酱料","pos":"n.","ipa":"","ex":"Could I have extra sauce on the side, please?"},
{"word":"dairy-free","zh":"无乳制品的","pos":"adj.","ipa":"","ex":"Do you have a dairy-free option? I'm lactose intolerant."},
{"word":"grilled","zh":"烤的","pos":"adj.","ipa":"","ex":"I'll have the grilled chicken breast with a green salad."},
{"word":"steamed","zh":"蒸的","pos":"adj.","ipa":"","ex":"Could you make the vegetables steamed rather than fried?"},
{"word":"fresh","zh":"新鲜的","pos":"adj.","ipa":"","ex":"All our seafood is fresh and delivered daily from the market."},
{"word":"organic","zh":"有机的","pos":"adj.","ipa":"","ex":"We use organic, locally sourced ingredients wherever possible."},
{"word":"complimentary bread","zh":"赠送的面包","pos":"n.","ipa":"","ex":"The waiter brought complimentary bread and butter to the table."},
{"word":"corkage fee","zh":"开瓶费","pos":"n.","ipa":"","ex":"There is a small corkage fee if you bring your own wine."},

# ── 8. Hospital & Medical (医院医疗) ─────────────────────────────────────
{"word":"doctor","zh":"医生","pos":"n.","ipa":"","ex":"The doctor said I need to rest for at least a week."},
{"word":"nurse","zh":"护士","pos":"n.","ipa":"","ex":"The nurse took my blood pressure and temperature on arrival."},
{"word":"patient","zh":"病人","pos":"n.","ipa":"","ex":"The waiting room was full of patients this morning."},
{"word":"appointment","zh":"就医预约","pos":"n.","ipa":"","ex":"I made an appointment with my GP for next Tuesday."},
{"word":"clinic","zh":"诊所","pos":"n.","ipa":"","ex":"There is a walk-in clinic open on weekends near the station."},
{"word":"hospital","zh":"医院","pos":"n.","ipa":"","ex":"She was admitted to hospital for emergency surgery last night."},
{"word":"emergency room","zh":"急诊室","pos":"n.","ipa":"","ex":"He was rushed to the emergency room after the car accident."},
{"word":"waiting room","zh":"候诊室","pos":"n.","ipa":"","ex":"Please take a seat in the waiting room—the doctor will see you soon."},
{"word":"prescription","zh":"处方","pos":"n.","ipa":"","ex":"The doctor wrote me a prescription for antibiotics."},
{"word":"medicine","zh":"药","pos":"n.","ipa":"","ex":"Take this medicine twice a day with food, not on an empty stomach."},
{"word":"tablet","zh":"药片","pos":"n.","ipa":"","ex":"Swallow the tablet whole with a full glass of water."},
{"word":"dosage","zh":"用量 / 剂量","pos":"n.","ipa":"","ex":"Do not exceed the recommended dosage stated on the label."},
{"word":"side effect","zh":"副作用","pos":"n.","ipa":"","ex":"Drowsiness is a common side effect of this antihistamine."},
{"word":"symptom","zh":"症状","pos":"n.","ipa":"","ex":"What are your main symptoms, and when did they first appear?"},
{"word":"diagnosis","zh":"诊断","pos":"n.","ipa":"","ex":"The doctor gave a preliminary diagnosis of a mild respiratory infection."},
{"word":"treatment","zh":"治疗","pos":"n.","ipa":"","ex":"The treatment involves a two-week course of antibiotics."},
{"word":"surgery","zh":"手术","pos":"n.","ipa":"","ex":"He had surgery on his knee after the sports injury last month."},
{"word":"recovery","zh":"康复","pos":"n.","ipa":"","ex":"Her recovery is going well—she should be home within the week."},
{"word":"discharge","zh":"出院","pos":"n./v.","ipa":"","ex":"The doctor will discharge him if the test results look normal."},
{"word":"health insurance","zh":"医疗保险","pos":"n.","ipa":"","ex":"Please bring your health insurance card when you visit the clinic."},
{"word":"referral","zh":"转诊","pos":"n.","ipa":"","ex":"You'll need a GP referral before seeing a specialist."},
{"word":"specialist","zh":"专科医生","pos":"n.","ipa":"","ex":"My GP referred me to a specialist for further tests."},
{"word":"GP","zh":"全科医生 / General Practitioner","pos":"n.","ipa":"","ex":"Register with a local GP as soon as you move to a new area."},
{"word":"blood test","zh":"血液检测","pos":"n.","ipa":"","ex":"The doctor ordered a blood test to check for vitamin deficiencies."},
{"word":"X-ray","zh":"X射线检查","pos":"n.","ipa":"","ex":"The nurse took an X-ray to check if the bone was fractured."},
{"word":"MRI","zh":"核磁共振","pos":"n.","ipa":"","ex":"The MRI scan showed no abnormalities in the brain."},
{"word":"blood pressure","zh":"血压","pos":"n.","ipa":"","ex":"Your blood pressure is slightly high—try to reduce salt intake."},
{"word":"temperature","zh":"体温","pos":"n.","ipa":"","ex":"The nurse checked my temperature—it was 38.5 degrees."},
{"word":"allergy","zh":"过敏","pos":"n.","ipa":"","ex":"I have a serious allergy to penicillin—please note it on my file."},
{"word":"injection","zh":"注射","pos":"n.","ipa":"","ex":"The nurse gave me an injection in my upper arm."},
{"word":"vaccination","zh":"疫苗接种","pos":"n.","ipa":"","ex":"Annual flu vaccination is recommended for elderly patients."},
{"word":"vaccine","zh":"疫苗","pos":"n.","ipa":"","ex":"The vaccine is free of charge for all children under five."},
{"word":"bandage","zh":"绷带","pos":"n.","ipa":"","ex":"The nurse cleaned the wound and wrapped it in a clean bandage."},
{"word":"wound","zh":"伤口","pos":"n.","ipa":"","ex":"Keep the wound clean and dry to prevent infection."},
{"word":"headache","zh":"头痛","pos":"n.","ipa":"","ex":"I've had a splitting headache since this morning—do you have aspirin?"},
{"word":"stomachache","zh":"胃痛 / 腹痛","pos":"n.","ipa":"","ex":"He complained of a stomachache after eating at the street stall."},
{"word":"fever","zh":"发烧","pos":"n.","ipa":"","ex":"She has a high fever—her temperature is 39 degrees Celsius."},
{"word":"cold","zh":"感冒","pos":"n.","ipa":"","ex":"I caught a cold and had to stay home for three days."},
{"word":"flu","zh":"流感","pos":"n.","ipa":"","ex":"The flu spread quickly through the entire office in January."},
{"word":"cough","zh":"咳嗽","pos":"n./v.","ipa":"","ex":"I've had a dry cough for over a week—should I see a doctor?"},
{"word":"runny nose","zh":"流鼻涕","pos":"phr.","ipa":"","ex":"He woke up with a runny nose and sore throat this morning."},
{"word":"sore throat","zh":"喉咙痛","pos":"n.","ipa":"","ex":"Gargling with salt water can soothe a sore throat."},
{"word":"infection","zh":"感染","pos":"n.","ipa":"","ex":"The wound became infected—she needs a course of antibiotics."},
{"word":"antibiotic","zh":"抗生素","pos":"n.","ipa":"","ex":"Finish the full course of antibiotics, even if you feel better."},
{"word":"painkiller","zh":"止痛药","pos":"n.","ipa":"","ex":"Take one painkiller every six hours if the pain is severe."},
{"word":"pharmacy","zh":"药房 / 药店","pos":"n.","ipa":"","ex":"The nearest 24-hour pharmacy is two blocks down the street."},
{"word":"medical record","zh":"病历","pos":"n.","ipa":"","ex":"Please bring your medical records when visiting a new hospital."},
{"word":"follow-up","zh":"复诊","pos":"n.","ipa":"","ex":"Book a follow-up appointment in two weeks to check your progress."},
{"word":"ambulance","zh":"救护车","pos":"n.","ipa":"","ex":"Call an ambulance immediately—he's not breathing properly."},
{"word":"emergency","zh":"紧急情况","pos":"n.","ipa":"","ex":"In a medical emergency, call 120 in China or 911 in the US."},
{"word":"fracture","zh":"骨折","pos":"n.","ipa":"","ex":"The X-ray confirmed she had a hairline fracture in her wrist."},
{"word":"sprain","zh":"扭伤","pos":"n./v.","ipa":"","ex":"I sprained my ankle while running and had to use crutches."},
{"word":"nausea","zh":"恶心","pos":"n.","ipa":"","ex":"She felt severe nausea after taking the medication on an empty stomach."},
{"word":"vomit","zh":"呕吐","pos":"v./n.","ipa":"","ex":"He vomited twice overnight, so we took him straight to the clinic."},
{"word":"diarrhea","zh":"腹泻","pos":"n.","ipa":"","ex":"Drink plenty of fluids if you have diarrhea to stay hydrated."},
{"word":"rash","zh":"皮疹","pos":"n.","ipa":"","ex":"She developed a red rash all over her arms after touching the plant."},
{"word":"dizzy","zh":"头晕的","pos":"adj.","ipa":"","ex":"I felt dizzy when I stood up too quickly from the chair."},
{"word":"faint","zh":"昏厥 / 晕倒","pos":"v./adj.","ipa":"","ex":"She fainted during the ceremony because of the extreme heat."},
{"word":"ward","zh":"病房","pos":"n.","ipa":"","ex":"He was moved from the ICU to a general ward after two days."},
{"word":"physical exam","zh":"体检","pos":"n.","ipa":"","ex":"A full physical exam is required before starting the new job."},
{"word":"chronic","zh":"慢性的","pos":"adj.","ipa":"","ex":"He manages his chronic back pain with physiotherapy and exercise."},
{"word":"second opinion","zh":"第二诊断意见","pos":"n.","ipa":"","ex":"I'd like to get a second opinion before agreeing to surgery."},
{"word":"consent form","zh":"知情同意书","pos":"n.","ipa":"","ex":"Sign the consent form before any surgical procedure can begin."},
{"word":"outpatient","zh":"门诊 / 门诊患者","pos":"adj./n.","ipa":"","ex":"The procedure is done on an outpatient basis—no overnight stay needed."},

# ── 9. Shopping (购物) ───────────────────────────────────────────────────
{"word":"shop","zh":"商店 / 购物","pos":"n./v.","ipa":"","ex":"I love to shop for fresh produce at the weekend market."},
{"word":"mall","zh":"购物中心","pos":"n.","ipa":"","ex":"The new mall has over 200 stores and a large food court."},
{"word":"sale","zh":"特卖 / 打折","pos":"n.","ipa":"","ex":"Everything in the store is 50% off during the annual sale."},
{"word":"discount","zh":"折扣","pos":"n.","ipa":"","ex":"Use this coupon code to get a 20% discount on your next order."},
{"word":"promotion","zh":"促销活动","pos":"n.","ipa":"","ex":"There's a buy-one-get-one-free promotion on all shoes this week."},
{"word":"coupon","zh":"优惠券","pos":"n.","ipa":"","ex":"I saved over 200 yuan by using coupons at the supermarket."},
{"word":"price tag","zh":"价格标签","pos":"n.","ipa":"","ex":"Check the price tag—this jacket costs more than I expected."},
{"word":"try on","zh":"试穿","pos":"phr.v.","ipa":"","ex":"Can I try on this dress in a size medium, please?"},
{"word":"fitting room","zh":"试衣间","pos":"n.","ipa":"","ex":"The fitting rooms are at the back of the store on the right."},
{"word":"exchange","zh":"换货","pos":"n./v.","ipa":"","ex":"Can I exchange this shirt for a larger size? It doesn't fit."},
{"word":"return","zh":"退货","pos":"n./v.","ipa":"","ex":"You can return the item within 30 days with the original receipt."},
{"word":"warranty","zh":"质保 / 保修","pos":"n.","ipa":"","ex":"The laptop comes with a two-year warranty covering all defects."},
{"word":"brand","zh":"品牌","pos":"n.","ipa":"","ex":"She only buys shoes from well-known international brands."},
{"word":"out of stock","zh":"缺货","pos":"phr.","ipa":"","ex":"Sorry, this colour is currently out of stock—check back next week."},
{"word":"sold out","zh":"售罄","pos":"phr.","ipa":"","ex":"The new model sold out within minutes of going on sale."},
{"word":"online shopping","zh":"网购","pos":"n.","ipa":"","ex":"Online shopping has become the default for most young consumers."},
{"word":"free shipping","zh":"免运费","pos":"phr.","ipa":"","ex":"Orders above 200 yuan qualify for free shipping to your door."},
{"word":"tracking number","zh":"快递单号","pos":"n.","ipa":"","ex":"Use your tracking number to check where your parcel is right now."},
{"word":"checkout","zh":"结账","pos":"n.","ipa":"","ex":"Add items to your cart and proceed to checkout when you're ready."},
{"word":"refund","zh":"退款","pos":"n./v.","ipa":"","ex":"The refund should appear in your account within five working days."},
{"word":"customer service","zh":"客户服务","pos":"n.","ipa":"","ex":"Contact customer service if your item arrives damaged."},
{"word":"bargain","zh":"便宜货 / 讨价还价","pos":"n./v.","ipa":"","ex":"You can often bargain at the night market and get a much better price."},
{"word":"second-hand","zh":"二手的","pos":"adj.","ipa":"","ex":"I bought a second-hand bicycle in great condition for a fraction of the price."},
{"word":"authentic","zh":"正品的","pos":"adj.","ipa":"","ex":"Always buy from official stores to ensure the product is authentic."},
{"word":"clearance","zh":"清仓","pos":"n.","ipa":"","ex":"They're having a clearance sale to make room for new stock."},
{"word":"limited edition","zh":"限量版","pos":"n.","ipa":"","ex":"This limited edition sneaker sold out in under ten minutes."},
{"word":"receipt","zh":"收据","pos":"n.","ipa":"","ex":"Keep your receipt—you'll need it if you want a refund."},
{"word":"gift wrap","zh":"礼品包装","pos":"n.","ipa":"","ex":"Would you like gift wrapping? It's free for purchases over 50 yuan."},
{"word":"duty free","zh":"免税","pos":"adj.","ipa":"","ex":"You can buy perfume and spirits duty free at the airport."},
{"word":"bestseller","zh":"畅销品","pos":"n.","ipa":"","ex":"This book has been on the bestseller list for six consecutive months."},
{"word":"defective","zh":"有缺陷的","pos":"adj.","ipa":"","ex":"They sent a defective item so I'm returning it for a replacement."},

# ── 10. Transportation (交通出行) ─────────────────────────────────────────
{"word":"metro","zh":"地铁 / 城铁","pos":"n.","ipa":"","ex":"Take the metro Line 2 and get off at People's Square station."},
{"word":"tram","zh":"有轨电车","pos":"n.","ipa":"","ex":"The historic tram runs along the waterfront every 15 minutes."},
{"word":"ride-share","zh":"顺风车 / 网约车","pos":"n.","ipa":"","ex":"Book a ride-share using the app—it's cheaper than a regular taxi."},
{"word":"fare","zh":"票价 / 车费","pos":"n.","ipa":"","ex":"The bus fare is 2 yuan for any distance within the city."},
{"word":"route","zh":"路线","pos":"n.","ipa":"","ex":"The fastest route to the airport avoids the city centre entirely."},
{"word":"platform","zh":"站台","pos":"n.","ipa":"","ex":"The train to Shanghai departs from Platform 5 in ten minutes."},
{"word":"rush hour","zh":"高峰时间","pos":"n.","ipa":"","ex":"Avoid taking the subway during rush hour if you can—it's packed."},
{"word":"traffic","zh":"交通 / 车流","pos":"n.","ipa":"","ex":"Heavy traffic on the ring road is causing delays of 40 minutes."},
{"word":"speed limit","zh":"限速","pos":"n.","ipa":"","ex":"The speed limit on this road is 60 km/h—slow down."},
{"word":"driver's license","zh":"驾驶执照","pos":"n.","ipa":"","ex":"You must carry your driver's license whenever you drive."},
{"word":"electric vehicle","zh":"电动汽车","pos":"n.","ipa":"","ex":"Electric vehicles are becoming more affordable and popular each year."},
{"word":"navigation","zh":"导航","pos":"n.","ipa":"","ex":"Turn on navigation—I'm not sure of the exact address."},
{"word":"detour","zh":"绕道 / 绕行","pos":"n./v.","ipa":"","ex":"We had to take a detour because of the road construction ahead."},
{"word":"pedestrian","zh":"行人","pos":"n.","ipa":"","ex":"Always give way to pedestrians at a crosswalk."},
{"word":"crosswalk","zh":"人行横道","pos":"n.","ipa":"","ex":"Wait for the green signal before crossing at the crosswalk."},
{"word":"traffic light","zh":"交通灯 / 红绿灯","pos":"n.","ipa":"","ex":"Turn left at the next set of traffic lights."},
{"word":"intersection","zh":"十字路口","pos":"n.","ipa":"","ex":"There was a minor collision at the intersection this morning."},
{"word":"U-turn","zh":"U形转弯","pos":"n.","ipa":"","ex":"Make a U-turn at the roundabout and head back the other way."},
{"word":"lane","zh":"车道","pos":"n.","ipa":"","ex":"Stay in the left lane when approaching the junction."},
{"word":"highway","zh":"高速公路","pos":"n.","ipa":"","ex":"We drove on the highway to avoid all the city centre traffic."},
{"word":"parking meter","zh":"停车计时器","pos":"n.","ipa":"","ex":"Pay the parking meter before you walk to the restaurant."},
{"word":"flat tire","zh":"爆胎","pos":"n.","ipa":"","ex":"We got a flat tire on the motorway and had to call for help."},
{"word":"breakdown","zh":"故障 / 抛锚","pos":"n.","ipa":"","ex":"The car had a breakdown in the middle of the tunnel."},
{"word":"seat belt","zh":"安全带","pos":"n.","ipa":"","ex":"Always buckle your seat belt before starting the engine."},
{"word":"car rental","zh":"租车","pos":"n.","ipa":"","ex":"Car rental is available at the airport with an international licence."},
{"word":"bicycle lane","zh":"自行车道","pos":"n.","ipa":"","ex":"Cyclists must stay in the designated bicycle lane at all times."},
{"word":"ferry","zh":"渡轮","pos":"n.","ipa":"","ex":"Take the ferry across the harbour—it only takes 10 minutes."},
{"word":"bus stop","zh":"公共汽车站","pos":"n.","ipa":"","ex":"The bus stop is right outside the hotel entrance on the main road."},
{"word":"transfer","zh":"换乘","pos":"n.","ipa":"","ex":"Transfer to Line 4 at the central station and ride for three stops."},
{"word":"timetable","zh":"时刻表","pos":"n.","ipa":"","ex":"Check the timetable before leaving—trains run less frequently on weekends."},

# ── 11. Banking & Finance (银行金融) ─────────────────────────────────────
{"word":"bank account","zh":"银行账户","pos":"n.","ipa":"","ex":"Open a bank account as soon as you arrive in a new country."},
{"word":"savings account","zh":"储蓄账户","pos":"n.","ipa":"","ex":"Move 20% of your paycheck into a savings account each month."},
{"word":"deposit","zh":"存款 / 存入","pos":"n./v.","ipa":"","ex":"You can deposit cash at any branch or via the ATM."},
{"word":"withdraw","zh":"取款","pos":"v.","ipa":"","ex":"I need to withdraw some local currency before the trip."},
{"word":"transfer","zh":"转账","pos":"n./v.","ipa":"","ex":"I'll transfer the money to your account by this afternoon."},
{"word":"wire transfer","zh":"电汇","pos":"n.","ipa":"","ex":"International wire transfers typically take one to three working days."},
{"word":"balance","zh":"余额","pos":"n.","ipa":"","ex":"Check your account balance before making a large purchase."},
{"word":"statement","zh":"账单 / 对账单","pos":"n.","ipa":"","ex":"Your monthly statement will be sent to your registered email address."},
{"word":"interest rate","zh":"利率","pos":"n.","ipa":"","ex":"The current interest rate on savings accounts is very low."},
{"word":"loan","zh":"贷款","pos":"n.","ipa":"","ex":"He took out a personal loan to pay for his education."},
{"word":"ATM","zh":"自动取款机 / Automated Teller Machine","pos":"n.","ipa":"","ex":"There's an ATM on every corner in this part of the city."},
{"word":"PIN","zh":"个人识别码 / Personal Identification Number","pos":"n.","ipa":"","ex":"Never share your PIN with anyone, not even bank staff."},
{"word":"debit card","zh":"借记卡","pos":"n.","ipa":"","ex":"I use my debit card for daily spending to avoid debt."},
{"word":"credit limit","zh":"信用额度","pos":"n.","ipa":"","ex":"You can apply to increase your credit limit after six months."},
{"word":"currency","zh":"货币","pos":"n.","ipa":"","ex":"Which currency do you need? We stock over 30 different ones."},
{"word":"foreign exchange","zh":"外汇","pos":"n.","ipa":"","ex":"You can exchange foreign currency at the bank or the airport."},
{"word":"transaction fee","zh":"交易手续费","pos":"n.","ipa":"","ex":"Some ATMs charge a foreign transaction fee—check yours first."},
{"word":"invest","zh":"投资","pos":"v.","ipa":"","ex":"She decided to invest part of her savings in index funds."},
{"word":"budget","zh":"预算","pos":"n.","ipa":"","ex":"Stick to your monthly budget to avoid overspending."},
{"word":"debt","zh":"债务","pos":"n.","ipa":"","ex":"Pay off high-interest debt before investing your spare cash."},
{"word":"credit score","zh":"信用评分","pos":"n.","ipa":"","ex":"A good credit score makes it easier to get a mortgage."},
{"word":"mortgage","zh":"房贷","pos":"n.","ipa":"","ex":"They applied for a 30-year mortgage to buy their first home."},
{"word":"insurance premium","zh":"保险费","pos":"n.","ipa":"","ex":"Your health insurance premium will be deducted from your paycheck."},
{"word":"direct debit","zh":"直接扣款","pos":"n.","ipa":"","ex":"Set up a direct debit so you never miss a rent payment."},
{"word":"overdraft","zh":"透支","pos":"n.","ipa":"","ex":"Avoid going into overdraft—the fees are very high."},
{"word":"net worth","zh":"净资产","pos":"n.","ipa":"","ex":"Calculate your net worth by subtracting liabilities from total assets."},
{"word":"paycheck","zh":"薪资 / 工资","pos":"n.","ipa":"","ex":"My paycheck is deposited directly into my bank account each month."},
{"word":"cash flow","zh":"现金流","pos":"n.","ipa":"","ex":"Managing cash flow carefully is essential for small businesses."},

# ── 12. Technology & Internet (科技网络) ──────────────────────────────────
{"word":"smartphone","zh":"智能手机","pos":"n.","ipa":"","ex":"Most people now use their smartphone as their primary camera."},
{"word":"tablet","zh":"平板电脑","pos":"n.","ipa":"","ex":"She uses a tablet for reading and watching videos on the commute."},
{"word":"app","zh":"应用程序","pos":"n.","ipa":"","ex":"Download the app and create an account to get started."},
{"word":"download","zh":"下载","pos":"v./n.","ipa":"","ex":"Download the software update—it fixes several security bugs."},
{"word":"upload","zh":"上传","pos":"v./n.","ipa":"","ex":"Upload the document to the shared folder so everyone can access it."},
{"word":"Wi-Fi","zh":"无线网络","pos":"n.","ipa":"","ex":"Is there free Wi-Fi here? I need to send an important email."},
{"word":"username","zh":"用户名","pos":"n.","ipa":"","ex":"Enter your username and password to log in to the platform."},
{"word":"log in","zh":"登录","pos":"phr.v.","ipa":"","ex":"I can't log in to my account—the password isn't working."},
{"word":"log out","zh":"退出登录","pos":"phr.v.","ipa":"","ex":"Always log out when using a shared or public computer."},
{"word":"update","zh":"更新","pos":"v./n.","ipa":"","ex":"Install the latest update to get new features and security fixes."},
{"word":"crash","zh":"崩溃 / 死机","pos":"v./n.","ipa":"","ex":"The app crashed and I lost all my unsaved work."},
{"word":"browser","zh":"浏览器","pos":"n.","ipa":"","ex":"Clear your browser cache if the website isn't loading properly."},
{"word":"notification","zh":"通知","pos":"n.","ipa":"","ex":"Turn off non-essential notifications so you can focus on work."},
{"word":"privacy settings","zh":"隐私设置","pos":"n.","ipa":"","ex":"Review your privacy settings on social media every few months."},
{"word":"cloud storage","zh":"云存储","pos":"n.","ipa":"","ex":"Back up your photos to cloud storage so you don't lose them."},
{"word":"backup","zh":"备份","pos":"n./v.","ipa":"","ex":"Always backup your data before performing a factory reset."},
{"word":"cybersecurity","zh":"网络安全","pos":"n.","ipa":"","ex":"Cybersecurity threats are increasing—use strong, unique passwords."},
{"word":"two-factor authentication","zh":"双重认证","pos":"n.","ipa":"","ex":"Enable two-factor authentication on all your important accounts."},
{"word":"VPN","zh":"虚拟专用网络 / Virtual Private Network","pos":"n.","ipa":"","ex":"Use a VPN when connecting to public Wi-Fi to protect your data."},
{"word":"software","zh":"软件","pos":"n.","ipa":"","ex":"The company uses project management software to track all tasks."},
{"word":"screenshot","zh":"截图","pos":"n.","ipa":"","ex":"Take a screenshot and send it to me so I can see the error."},
{"word":"video call","zh":"视频通话","pos":"n.","ipa":"","ex":"Let's have a quick video call instead of writing a long email."},
{"word":"social media","zh":"社交媒体","pos":"n.","ipa":"","ex":"Limit your social media time to avoid distraction during work hours."},
{"word":"streaming","zh":"流媒体","pos":"n.","ipa":"","ex":"Streaming services have largely replaced traditional cable TV."},
{"word":"phishing","zh":"网络钓鱼","pos":"n.","ipa":"","ex":"Never click links in suspicious emails—they could be phishing attacks."},
{"word":"spam","zh":"垃圾邮件","pos":"n.","ipa":"","ex":"Mark the email as spam so your inbox stays clean and organised."},
{"word":"QR code","zh":"二维码","pos":"n.","ipa":"","ex":"Scan the QR code to access the digital menu on your phone."},
{"word":"charger","zh":"充电器","pos":"n.","ipa":"","ex":"Could I borrow a phone charger? My battery is almost dead."},

# ── 13. Weather & Environment (天气环境) ──────────────────────────────────
{"word":"sunny","zh":"晴朗的","pos":"adj.","ipa":"","ex":"It's a beautiful sunny day—perfect for a walk in the park."},
{"word":"cloudy","zh":"多云的","pos":"adj.","ipa":"","ex":"It's cloudy today but it shouldn't rain until this evening."},
{"word":"rainy","zh":"下雨的","pos":"adj.","ipa":"","ex":"It's been rainy all week—I haven't seen the sun in days."},
{"word":"snowy","zh":"下雪的","pos":"adj.","ipa":"","ex":"The roads are slippery after a snowy night—drive carefully."},
{"word":"windy","zh":"刮风的","pos":"adj.","ipa":"","ex":"It's very windy today—hold on to your hat!"},
{"word":"foggy","zh":"有雾的","pos":"adj.","ipa":"","ex":"The foggy conditions caused several flight delays this morning."},
{"word":"humid","zh":"潮湿的","pos":"adj.","ipa":"","ex":"Summers here are incredibly humid—the air feels heavy and sticky."},
{"word":"freezing","zh":"极寒的 / 冰冻的","pos":"adj.","ipa":"","ex":"It's absolutely freezing outside—wear your warmest coat."},
{"word":"storm","zh":"暴风雨","pos":"n.","ipa":"","ex":"A severe storm is forecast for the weekend—stay indoors if possible."},
{"word":"thunder","zh":"雷声","pos":"n.","ipa":"","ex":"I could hear loud thunder in the distance all evening."},
{"word":"lightning","zh":"闪电","pos":"n.","ipa":"","ex":"Stay away from tall trees during a lightning storm."},
{"word":"forecast","zh":"天气预报","pos":"n.","ipa":"","ex":"According to the forecast, it will rain heavily tomorrow afternoon."},
{"word":"temperature","zh":"温度","pos":"n.","ipa":"","ex":"The temperature is expected to drop to below zero overnight."},
{"word":"Celsius","zh":"摄氏度","pos":"n.","ipa":"","ex":"It's 38 degrees Celsius in the shade today—drink plenty of water."},
{"word":"umbrella","zh":"雨伞","pos":"n.","ipa":"","ex":"Take an umbrella—the sky looks like it's about to pour."},
{"word":"raincoat","zh":"雨衣","pos":"n.","ipa":"","ex":"I wore a raincoat but still got completely soaked."},
{"word":"sunscreen","zh":"防晒霜","pos":"n.","ipa":"","ex":"Apply sunscreen before going to the beach to avoid sunburn."},
{"word":"heatwave","zh":"热浪","pos":"n.","ipa":"","ex":"A heatwave hit the region, breaking 60-year temperature records."},
{"word":"flood","zh":"洪水","pos":"n.","ipa":"","ex":"Heavy rainfall caused flooding in the low-lying parts of the city."},
{"word":"drought","zh":"干旱","pos":"n.","ipa":"","ex":"The prolonged drought damaged crops across the entire region."},
{"word":"season","zh":"季节","pos":"n.","ipa":"","ex":"What season is the best time to visit your country?"},
{"word":"spring","zh":"春天","pos":"n.","ipa":"","ex":"Cherry blossoms bloom beautifully in spring across Japan."},
{"word":"autumn","zh":"秋天 / 秋季","pos":"n.","ipa":"","ex":"The autumn leaves turn brilliant shades of red and gold."},

# ── 14. Emotions & Feelings (情感表达) ───────────────────────────────────
{"word":"happy","zh":"开心的","pos":"adj.","ipa":"","ex":"I'm so happy to hear that you got the job—well done!"},
{"word":"sad","zh":"悲伤的","pos":"adj.","ipa":"","ex":"She felt sad after saying goodbye to her friends at the airport."},
{"word":"angry","zh":"愤怒的","pos":"adj.","ipa":"","ex":"He got very angry when he found out about the mistake."},
{"word":"excited","zh":"兴奋的","pos":"adj.","ipa":"","ex":"The children were so excited about the upcoming school trip."},
{"word":"nervous","zh":"紧张的","pos":"adj.","ipa":"","ex":"She was nervous before the presentation but did really well."},
{"word":"worried","zh":"担忧的","pos":"adj.","ipa":"","ex":"I'm worried about my father's health—he hasn't been well lately."},
{"word":"confused","zh":"困惑的","pos":"adj.","ipa":"","ex":"I'm a bit confused—could you explain that point again?"},
{"word":"surprised","zh":"惊讶的","pos":"adj.","ipa":"","ex":"I was completely surprised by the unexpected promotion."},
{"word":"disappointed","zh":"失望的","pos":"adj.","ipa":"","ex":"We were disappointed when the concert was cancelled last minute."},
{"word":"satisfied","zh":"满意的","pos":"adj.","ipa":"","ex":"I'm very satisfied with the quality of the service I received."},
{"word":"frustrated","zh":"沮丧的 / 挫败的","pos":"adj.","ipa":"","ex":"I get so frustrated when the internet connection keeps dropping."},
{"word":"grateful","zh":"感激的","pos":"adj.","ipa":"","ex":"I'm truly grateful for all the support you've given me this year."},
{"word":"proud","zh":"骄傲的","pos":"adj.","ipa":"","ex":"Her parents were incredibly proud when she graduated top of her class."},
{"word":"embarrassed","zh":"尴尬的","pos":"adj.","ipa":"","ex":"I was so embarrassed when I forgot his name during introductions."},
{"word":"bored","zh":"无聊的","pos":"adj.","ipa":"","ex":"I'm bored of doing the same tasks every day—I need a new challenge."},
{"word":"tired","zh":"疲惫的","pos":"adj.","ipa":"","ex":"I'm absolutely tired after working 12 hours straight today."},
{"word":"stressed","zh":"压力大的","pos":"adj.","ipa":"","ex":"She's very stressed about the upcoming deadlines and presentations."},
{"word":"relaxed","zh":"放松的","pos":"adj.","ipa":"","ex":"I feel completely relaxed after a week of holiday by the sea."},
{"word":"confident","zh":"自信的","pos":"adj.","ipa":"","ex":"He walked into the interview looking calm and confident."},
{"word":"overwhelmed","zh":"不知所措的","pos":"adj.","ipa":"","ex":"I feel completely overwhelmed with everything on my plate right now."},
{"word":"motivated","zh":"有动力的","pos":"adj.","ipa":"","ex":"The inspiring speech left the whole team feeling motivated."},
{"word":"optimistic","zh":"乐观的","pos":"adj.","ipa":"","ex":"Despite the challenges, she remains optimistic about the future."},
{"word":"anxious","zh":"焦虑的","pos":"adj.","ipa":"","ex":"I always feel anxious when I have to speak in front of a large crowd."},
{"word":"relieved","zh":"如释重负的","pos":"adj.","ipa":"","ex":"I was so relieved when I heard the test results came back negative."},
{"word":"homesick","zh":"思乡的","pos":"adj.","ipa":"","ex":"I started feeling homesick after my first month living abroad."},
{"word":"lonely","zh":"孤独的","pos":"adj.","ipa":"","ex":"Moving to a new city can be lonely before you make new friends."},
{"word":"cheerful","zh":"开朗的","pos":"adj.","ipa":"","ex":"She's always cheerful and positive, even on difficult days."},
{"word":"calm","zh":"冷静的","pos":"adj.","ipa":"","ex":"Stay calm and think clearly—panic won't help the situation."},
{"word":"curious","zh":"好奇的","pos":"adj.","ipa":"","ex":"Children are naturally curious about the world around them."},
{"word":"jealous","zh":"嫉妒的","pos":"adj.","ipa":"","ex":"He felt a little jealous of his colleague's quick promotion."},

# ── 15. Common Phrases & Time (常用短语与时间) ────────────────────────────
{"word":"I need...","zh":"我需要…","pos":"phr.","ipa":"","ex":"I need a taxi to the airport as soon as possible."},
{"word":"Can I have...?","zh":"我可以要…吗？","pos":"phr.","ipa":"","ex":"Can I have a glass of water and the menu, please?"},
{"word":"Could you...?","zh":"您能…吗？","pos":"phr.","ipa":"","ex":"Could you help me carry this luggage to my room?"},
{"word":"Would you mind...?","zh":"你介意…吗？","pos":"phr.","ipa":"","ex":"Would you mind turning down the music a little?"},
{"word":"Is it possible to...?","zh":"…可能吗？","pos":"phr.","ipa":"","ex":"Is it possible to get a refund if I cancel the booking?"},
{"word":"How much is...?","zh":"…多少钱？","pos":"phr.","ipa":"","ex":"How much is a single room for one night?"},
{"word":"Where is...?","zh":"…在哪里？","pos":"phr.","ipa":"","ex":"Excuse me, where is the nearest pharmacy?"},
{"word":"What time is...?","zh":"…几点？","pos":"phr.","ipa":"","ex":"What time is the last train to the airport?"},
{"word":"How long does it take?","zh":"要多长时间？","pos":"phr.","ipa":"","ex":"How long does it take to walk to the city centre from here?"},
{"word":"Can you help me?","zh":"你能帮我吗？","pos":"phr.","ipa":"","ex":"Can you help me fill out this form in English?"},
{"word":"I'm looking for...","zh":"我在找…","pos":"phr.","ipa":"","ex":"I'm looking for a pharmacy near the hotel."},
{"word":"Do you have...?","zh":"你有…吗？","pos":"phr.","ipa":"","ex":"Do you have any rooms available for tonight?"},
{"word":"I'd like to...","zh":"我想…","pos":"phr.","ipa":"","ex":"I'd like to make a reservation for dinner this evening."},
{"word":"Just a moment","zh":"请稍等","pos":"phr.","ipa":"","ex":"Just a moment—let me check my diary for an available slot."},
{"word":"Hold on","zh":"等一下","pos":"phr.","ipa":"","ex":"Hold on—I'll transfer you to the right department now."},
{"word":"After you","zh":"您先请","pos":"phr.","ipa":"","ex":"After you—please go ahead and enter first."},
{"word":"Go ahead","zh":"请便 / 继续","pos":"phr.","ipa":"","ex":"Go ahead with the plan—we all agree it's the best approach."},
{"word":"No worries","zh":"不用担心","pos":"phr.","ipa":"","ex":"No worries! Take your time—there's no rush at all."},
{"word":"on time","zh":"准时","pos":"phr.","ipa":"","ex":"The train arrived exactly on time—very impressive."},
{"word":"running late","zh":"要迟到了","pos":"phr.","ipa":"","ex":"I'm running late—please start the meeting without me."},
{"word":"as soon as possible","zh":"尽快","pos":"phr.","ipa":"","ex":"Please send me the revised document as soon as possible."},
{"word":"in advance","zh":"提前","pos":"phr.","ipa":"","ex":"Book your tickets in advance to get the best available price."},
{"word":"at the moment","zh":"目前 / 此刻","pos":"phr.","ipa":"","ex":"I'm busy at the moment—can I call you back in ten minutes?"},
{"word":"in the meantime","zh":"在此期间","pos":"phr.","ipa":"","ex":"In the meantime, please review the draft and leave comments."},
{"word":"first of all","zh":"首先","pos":"phr.","ipa":"","ex":"First of all, let me thank everyone for coming today."},
{"word":"at least","zh":"至少","pos":"phr.","ipa":"","ex":"You should drink at least eight glasses of water per day."},
{"word":"approximately","zh":"大约","pos":"adv.","ipa":"","ex":"The journey takes approximately two hours by train."},
{"word":"according to","zh":"根据","pos":"prep.","ipa":"","ex":"According to the weather forecast, it will snow tomorrow."},
{"word":"despite","zh":"尽管","pos":"prep.","ipa":"","ex":"Despite the heavy rain, the match continued as planned."},
{"word":"although","zh":"虽然","pos":"conj.","ipa":"","ex":"Although it was expensive, the holiday was absolutely worth it."},
{"word":"unless","zh":"除非","pos":"conj.","ipa":"","ex":"Don't sign the contract unless you've read every clause."},
{"word":"in case","zh":"以防","pos":"phr.","ipa":"","ex":"Bring an umbrella in case it rains later this afternoon."},
{"word":"as long as","zh":"只要","pos":"phr.","ipa":"","ex":"As long as you finish by Friday, the method doesn't matter."},
{"word":"in order to","zh":"为了","pos":"phr.","ipa":"","ex":"In order to improve your English, you need daily practice."},
{"word":"due to","zh":"由于","pos":"prep.","ipa":"","ex":"The event was cancelled due to unforeseen circumstances."},
{"word":"regardless of","zh":"不管","pos":"prep.","ipa":"","ex":"We will proceed regardless of the outcome of the vote."},
{"word":"in my opinion","zh":"在我看来","pos":"phr.","ipa":"","ex":"In my opinion, we should invest more in customer service."},
{"word":"as far as I know","zh":"据我所知","pos":"phr.","ipa":"","ex":"As far as I know, no one has reported the same issue before."},
{"word":"to be honest","zh":"说实话","pos":"phr.","ipa":"","ex":"To be honest, I'm not entirely convinced by this proposal."},
{"word":"keep in mind","zh":"请记住","pos":"phr.","ipa":"","ex":"Keep in mind that the deadline is non-negotiable this time."},
{"word":"at the end of the day","zh":"归根到底","pos":"phr.","ipa":"","ex":"At the end of the day, what matters most is the result."},
{"word":"long story short","zh":"长话短说","pos":"phr.","ipa":"","ex":"Long story short, we lost the contract because of a typo."},
{"word":"give it a shot","zh":"试试看","pos":"phr.","ipa":"","ex":"I've never cooked Thai food before, but I'll give it a shot."},
{"word":"hang in there","zh":"坚持住","pos":"phr.","ipa":"","ex":"Hang in there—things will get easier once you settle in."},
{"word":"take it easy","zh":"放轻松","pos":"phr.","ipa":"","ex":"Take it easy this weekend—you've been working too hard lately."},
{"word":"so far so good","zh":"到目前为止还不错","pos":"phr.","ipa":"","ex":"So far so good—we're on track and within budget."},
{"word":"it depends","zh":"看情况","pos":"phr.","ipa":"","ex":"Should I bring a jacket? It depends on the weather tomorrow."},
{"word":"that being said","zh":"话虽如此","pos":"phr.","ipa":"","ex":"That being said, we should still be careful about the risks."},
{"word":"more or less","zh":"或多或少 / 大致","pos":"phr.","ipa":"","ex":"The project is more or less finished—just a few tweaks left."},
{"word":"off the top of my head","zh":"不假思索地","pos":"phr.","ipa":"","ex":"Off the top of my head, I'd say the cost is around $500."},
{"word":"between you and me","zh":"这是咱们之间的话","pos":"phr.","ipa":"","ex":"Between you and me, I think the manager made the wrong call."},
{"word":"fingers crossed","zh":"祈祷好运","pos":"phr.","ipa":"","ex":"My exam results come out tomorrow—fingers crossed!"},
{"word":"better safe than sorry","zh":"小心驶得万年船","pos":"phr.","ipa":"","ex":"Back up your files—better safe than sorry."},
{"word":"once in a while","zh":"偶尔","pos":"phr.","ipa":"","ex":"I treat myself to a nice dinner out once in a while."},
{"word":"right away","zh":"马上","pos":"phr.","ipa":"","ex":"I'll get back to you with the figures right away."},
{"word":"what's up","zh":"怎么了 / 最近咋样","pos":"phr.","ipa":"","ex":"Hey, what's up? You look a bit worried today."},
{"word":"catch up","zh":"叙旧 / 赶上","pos":"phr.v.","ipa":"","ex":"Let's grab a coffee and catch up—it's been ages!"},
{"word":"show up","zh":"出现 / 露面","pos":"phr.v.","ipa":"","ex":"He promised to show up by nine but still hasn't arrived."},
{"word":"figure out","zh":"弄明白 / 解决","pos":"phr.v.","ipa":"","ex":"I'll figure out the best route before we leave tomorrow."},
{"word":"look forward to","zh":"期待","pos":"phr.v.","ipa":"","ex":"I really look forward to seeing you at the conference next week."},
{"word":"deal with","zh":"处理 / 应对","pos":"phr.v.","ipa":"","ex":"I need to deal with this complaint before it escalates further."},
{"word":"count on","zh":"依靠 / 信赖","pos":"phr.v.","ipa":"","ex":"You can always count on her to deliver excellent work on time."},
{"word":"come up with","zh":"想出 / 提出","pos":"phr.v.","ipa":"","ex":"Let's come up with a solution before the client meeting tomorrow."},
{"word":"go over","zh":"仔细检查 / 过一遍","pos":"phr.v.","ipa":"","ex":"Let's go over the agenda one more time before the meeting starts."},
{"word":"bring up","zh":"提起 / 提出","pos":"phr.v.","ipa":"","ex":"I need to bring up the budget issue at the next team meeting."},
{"word":"turn down","zh":"拒绝 / 调低","pos":"phr.v.","ipa":"","ex":"She turned down the job offer because the salary was too low."},
{"word":"run out of","zh":"用完 / 耗尽","pos":"phr.v.","ipa":"","ex":"We've run out of milk—could you pick some up on the way home?"},
{"word":"put off","zh":"推迟","pos":"phr.v.","ipa":"","ex":"Don't put off dealing with difficult emails—reply the same day."},
{"word":"set up","zh":"建立 / 安排","pos":"phr.v.","ipa":"","ex":"Let me set up a meeting for the three of us next Monday morning."},
{"word":"check out","zh":"查看 / 了解","pos":"phr.v.","ipa":"","ex":"Check out this article—it's directly relevant to what we discussed."},
{"word":"get back to","zh":"回复 / 回头联系","pos":"phr.v.","ipa":"","ex":"I'll get back to you with a decision by the end of business today."},
]

out = pathlib.Path(__file__).parent.parent / 'game' / 'daily-words-1000.json'
out.write_text(json.dumps(WORDS, ensure_ascii=False, indent=2), encoding='utf-8')
print(f"Done. Written {len(WORDS)} entries to {out.name}.")
