#!/usr/bin/env python3
"""Append extra entries to daily-words-1000.json to reach ~1000 total."""
import json, pathlib

EXTRA = [
# ── 16. Numbers, Time & Calendar (时间与日历) ─────────────────────────────
{"word":"o'clock","zh":"…点整","pos":"n.","ipa":"","ex":"The meeting starts at nine o'clock sharp—don't be late."},
{"word":"half past","zh":"…点半","pos":"phr.","ipa":"","ex":"It's half past two—let's take a short break."},
{"word":"quarter to","zh":"差一刻…","pos":"phr.","ipa":"","ex":"It's quarter to eight—we need to leave now or we'll miss the bus."},
{"word":"noon","zh":"正午","pos":"n.","ipa":"","ex":"Let's meet for lunch at noon outside the office."},
{"word":"midnight","zh":"午夜","pos":"n.","ipa":"","ex":"The flight lands at midnight, so I'll take a taxi home."},
{"word":"morning","zh":"早上 / 上午","pos":"n.","ipa":"","ex":"I'm most productive in the morning before the emails pile up."},
{"word":"afternoon","zh":"下午","pos":"n.","ipa":"","ex":"The workshop runs from two to five in the afternoon."},
{"word":"evening","zh":"傍晚 / 晚上","pos":"n.","ipa":"","ex":"We're going to a jazz concert tomorrow evening."},
{"word":"tonight","zh":"今晚","pos":"adv.","ipa":"","ex":"Are you free for dinner tonight? I know a great new place."},
{"word":"yesterday","zh":"昨天","pos":"adv.","ipa":"","ex":"I submitted the report yesterday—did you get a chance to read it?"},
{"word":"tomorrow","zh":"明天","pos":"adv.","ipa":"","ex":"Tomorrow is my last day at this company."},
{"word":"day after tomorrow","zh":"后天","pos":"phr.","ipa":"","ex":"The parcel is expected to arrive the day after tomorrow."},
{"word":"weekend","zh":"周末","pos":"n.","ipa":"","ex":"Do you have any plans for the coming weekend?"},
{"word":"weekday","zh":"工作日","pos":"n.","ipa":"","ex":"The office is only open on weekdays, nine to six."},
{"word":"Monday","zh":"周一","pos":"n.","ipa":"","ex":"The project kickoff is scheduled for Monday morning."},
{"word":"Friday","zh":"周五","pos":"n.","ipa":"","ex":"Everyone looks forward to Friday afternoon."},
{"word":"punctual","zh":"准时的","pos":"adj.","ipa":"","ex":"He is always punctual—never a minute late for any meeting."},
{"word":"annual","zh":"年度的 / 每年的","pos":"adj.","ipa":"","ex":"The annual team retreat is held every September in the mountains."},
{"word":"monthly","zh":"每月的","pos":"adj.","ipa":"","ex":"A monthly newsletter is sent to all registered members."},
{"word":"weekly","zh":"每周的","pos":"adj.","ipa":"","ex":"We have a weekly check-in call every Monday at 9 a.m."},
{"word":"daily","zh":"每天的","pos":"adj.","ipa":"","ex":"Reading for 30 minutes daily can significantly improve your vocabulary."},
{"word":"deadline","zh":"截止时间","pos":"n.","ipa":"","ex":"The submission deadline is midnight on the 31st."},
{"word":"duration","zh":"时长 / 持续时间","pos":"n.","ipa":"","ex":"The course has a total duration of six weeks."},
{"word":"expire","zh":"到期 / 过期","pos":"v.","ipa":"","ex":"Your membership will expire at the end of this month."},
{"word":"postpone","zh":"推迟","pos":"v.","ipa":"","ex":"We had to postpone the launch to next quarter."},
{"word":"immediately","zh":"立刻","pos":"adv.","ipa":"","ex":"Please respond immediately—this is an urgent matter."},
{"word":"recently","zh":"最近","pos":"adv.","ipa":"","ex":"I recently started learning Spanish online in my spare time."},
{"word":"frequently","zh":"经常","pos":"adv.","ipa":"","ex":"She travels frequently for work—at least twice a month."},
{"word":"occasionally","zh":"偶尔","pos":"adv.","ipa":"","ex":"I occasionally work from a café to change my environment."},
{"word":"meanwhile","zh":"与此同时","pos":"adv.","ipa":"","ex":"Meanwhile, the second team continued working on the report."},
{"word":"eventually","zh":"最终","pos":"adv.","ipa":"","ex":"He struggled at first but eventually passed the exam."},
{"word":"prior to","zh":"在…之前","pos":"prep.","ipa":"","ex":"Please review the materials prior to attending the training."},

# ── 17. Education (教育) ─────────────────────────────────────────────────
{"word":"school","zh":"学校","pos":"n.","ipa":"","ex":"My children go to an international school near our home."},
{"word":"university","zh":"大学","pos":"n.","ipa":"","ex":"She graduated from university with a degree in economics."},
{"word":"degree","zh":"学位","pos":"n.","ipa":"","ex":"A bachelor's degree is the minimum requirement for this position."},
{"word":"major","zh":"主修专业","pos":"n.","ipa":"","ex":"Her major is computer science with a minor in mathematics."},
{"word":"professor","zh":"教授","pos":"n.","ipa":"","ex":"The professor gave a fascinating lecture on global economics."},
{"word":"lecture","zh":"讲座 / 课","pos":"n.","ipa":"","ex":"The morning lecture runs from 8 to 10 a.m. in Hall B."},
{"word":"assignment","zh":"作业 / 任务","pos":"n.","ipa":"","ex":"Submit your assignment through the online portal by Friday."},
{"word":"exam","zh":"考试","pos":"n.","ipa":"","ex":"I have a final exam next Monday—I need to start studying now."},
{"word":"grade","zh":"成绩 / 年级","pos":"n.","ipa":"","ex":"She got excellent grades throughout all four years of college."},
{"word":"scholarship","zh":"奖学金","pos":"n.","ipa":"","ex":"He won a full scholarship to study abroad at a top university."},
{"word":"tuition","zh":"学费","pos":"n.","ipa":"","ex":"University tuition fees have increased significantly this year."},
{"word":"campus","zh":"校园","pos":"n.","ipa":"","ex":"The campus is large and has its own gym, library, and cafeteria."},
{"word":"library","zh":"图书馆","pos":"n.","ipa":"","ex":"I reserved a study room at the library for the afternoon."},
{"word":"semester","zh":"学期","pos":"n.","ipa":"","ex":"The new semester begins in early September after the summer break."},
{"word":"graduate","zh":"毕业 / 毕业生","pos":"v./n.","ipa":"","ex":"She graduated with first-class honours from a top-ranked university."},
{"word":"enrol","zh":"注册 / 报名","pos":"v.","ipa":"","ex":"Enrol in the online course before the registration deadline."},
{"word":"certificate","zh":"证书","pos":"n.","ipa":"","ex":"You'll receive a certificate upon completing the full programme."},
{"word":"curriculum","zh":"课程体系","pos":"n.","ipa":"","ex":"The curriculum covers both theory and practical application."},
{"word":"textbook","zh":"教材 / 课本","pos":"n.","ipa":"","ex":"The required textbook is available in both print and digital formats."},
{"word":"note-taking","zh":"记笔记","pos":"n.","ipa":"","ex":"Effective note-taking helps you retain information much longer."},
{"word":"homework","zh":"家庭作业","pos":"n.","ipa":"","ex":"The teacher assigns homework every evening to reinforce the lesson."},

# ── 18. Food & Cooking (食物与烹饪) ──────────────────────────────────────
{"word":"ingredient","zh":"食材 / 原料","pos":"n.","ipa":"","ex":"Gather all the ingredients before you start cooking."},
{"word":"recipe","zh":"食谱","pos":"n.","ipa":"","ex":"I found a simple recipe for homemade pasta online."},
{"word":"chop","zh":"切碎","pos":"v.","ipa":"","ex":"Chop the onions finely and fry them until golden."},
{"word":"fry","zh":"炒 / 炸","pos":"v.","ipa":"","ex":"Fry the garlic in olive oil over medium heat."},
{"word":"boil","zh":"煮沸","pos":"v.","ipa":"","ex":"Boil the pasta for ten minutes and then drain it."},
{"word":"marinate","zh":"腌制","pos":"v.","ipa":"","ex":"Marinate the chicken overnight for the best flavour."},
{"word":"seasoning","zh":"调味料","pos":"n.","ipa":"","ex":"Add seasoning to taste—salt, pepper, and a pinch of paprika."},
{"word":"portion","zh":"份量","pos":"n.","ipa":"","ex":"One portion of rice is about 75 grams of dry grain."},
{"word":"frozen food","zh":"冷冻食品","pos":"n.","ipa":"","ex":"Stock up on frozen food so you always have a quick meal option."},
{"word":"snack","zh":"零食","pos":"n.","ipa":"","ex":"I keep healthy snacks at my desk to avoid vending machine temptation."},
{"word":"cuisine","zh":"菜系 / 烹饪风格","pos":"n.","ipa":"","ex":"Italian cuisine is loved worldwide for its simplicity and flavour."},
{"word":"spice","zh":"香料 / 调料","pos":"n.","ipa":"","ex":"Indian cooking uses a wide variety of aromatic spices."},
{"word":"herb","zh":"香草 / 药草","pos":"n.","ipa":"","ex":"Fresh herbs like basil and rosemary enhance any dish."},
{"word":"vegetable","zh":"蔬菜","pos":"n.","ipa":"","ex":"Try to include a variety of colourful vegetables in every meal."},
{"word":"fruit","zh":"水果","pos":"n.","ipa":"","ex":"Eating two portions of fruit per day is good for your health."},
{"word":"protein","zh":"蛋白质","pos":"n.","ipa":"","ex":"Chicken, fish, and beans are all excellent sources of protein."},
{"word":"carbohydrate","zh":"碳水化合物","pos":"n.","ipa":"","ex":"Rice, bread, and pasta are all high in carbohydrates."},
{"word":"nutrition","zh":"营养","pos":"n.","ipa":"","ex":"Good nutrition is as important as regular exercise for good health."},
{"word":"calorie","zh":"卡路里","pos":"n.","ipa":"","ex":"This dessert contains over 600 calories—quite indulgent!"},
{"word":"diet","zh":"饮食 / 节食","pos":"n.","ipa":"","ex":"A balanced diet includes plenty of vegetables, lean protein, and whole grains."},
{"word":"junk food","zh":"垃圾食品","pos":"n.","ipa":"","ex":"Try to limit junk food to an occasional treat rather than a daily habit."},

# ── 19. Sports & Leisure (运动与休闲) ────────────────────────────────────
{"word":"exercise","zh":"锻炼","pos":"n./v.","ipa":"","ex":"Regular exercise improves both physical and mental wellbeing."},
{"word":"gym","zh":"健身房","pos":"n.","ipa":"","ex":"I go to the gym three times a week after work."},
{"word":"jogging","zh":"慢跑","pos":"n.","ipa":"","ex":"Early morning jogging is a great way to start the day."},
{"word":"yoga","zh":"瑜伽","pos":"n.","ipa":"","ex":"She does yoga every morning to improve flexibility and reduce stress."},
{"word":"swimming","zh":"游泳","pos":"n.","ipa":"","ex":"Swimming is one of the best full-body exercises available."},
{"word":"cycling","zh":"骑自行车","pos":"n.","ipa":"","ex":"Cycling to work is both eco-friendly and great exercise."},
{"word":"match","zh":"比赛","pos":"n.","ipa":"","ex":"The football match starts at 8 p.m.—want to watch it together?"},
{"word":"team sport","zh":"团体运动","pos":"n.","ipa":"","ex":"Team sports build collaboration and communication skills."},
{"word":"coach","zh":"教练","pos":"n.","ipa":"","ex":"The coach gave a motivating team talk before the final."},
{"word":"tournament","zh":"锦标赛","pos":"n.","ipa":"","ex":"Our company is entering a table tennis tournament next month."},
{"word":"hobby","zh":"爱好","pos":"n.","ipa":"","ex":"My hobbies include reading, cooking, and hiking in the mountains."},
{"word":"travel","zh":"旅行","pos":"n./v.","ipa":"","ex":"I love to travel to new places whenever I have the chance."},
{"word":"concert","zh":"音乐会","pos":"n.","ipa":"","ex":"We have tickets to a jazz concert downtown this Saturday."},
{"word":"exhibition","zh":"展览","pos":"n.","ipa":"","ex":"There's a fantastic photography exhibition at the gallery this month."},
{"word":"cinema","zh":"电影院","pos":"n.","ipa":"","ex":"Let's catch a movie at the cinema after dinner tonight."},
{"word":"theatre","zh":"剧场 / 剧院","pos":"n.","ipa":"","ex":"We saw an amazing play at the West End theatre last weekend."},
{"word":"photography","zh":"摄影","pos":"n.","ipa":"","ex":"He takes up photography as a hobby and has a great eye for detail."},
{"word":"weekend getaway","zh":"周末短途旅行","pos":"n.","ipa":"","ex":"A weekend getaway to the countryside is just what we need."},
{"word":"staycation","zh":"居家度假","pos":"n.","ipa":"","ex":"We had a staycation this summer and explored our own city."},

# ── 20. Body & Health (身体与健康) ────────────────────────────────────────
{"word":"headache","zh":"头痛","pos":"n.","ipa":"","ex":"I've had a pounding headache since this morning."},
{"word":"backache","zh":"背痛","pos":"n.","ipa":"","ex":"Sitting at a desk all day can cause chronic backache."},
{"word":"toothache","zh":"牙痛","pos":"n.","ipa":"","ex":"My toothache has been unbearable—I need to see a dentist today."},
{"word":"sleep","zh":"睡眠 / 睡觉","pos":"n./v.","ipa":"","ex":"Most adults need between seven and nine hours of sleep each night."},
{"word":"healthy","zh":"健康的","pos":"adj.","ipa":"","ex":"Maintaining a healthy lifestyle reduces the risk of many diseases."},
{"word":"fit","zh":"健康的 / 合适的","pos":"adj.","ipa":"","ex":"She keeps fit by running five kilometres every morning."},
{"word":"overweight","zh":"超重的","pos":"adj.","ipa":"","ex":"Being overweight increases the risk of heart disease and diabetes."},
{"word":"weight","zh":"体重","pos":"n.","ipa":"","ex":"His doctor advised him to watch his weight and cut down on sugar."},
{"word":"dentist","zh":"牙医","pos":"n.","ipa":"","ex":"I go to the dentist for a check-up every six months."},
{"word":"optician","zh":"眼科医生 / 眼镜师","pos":"n.","ipa":"","ex":"I need to visit the optician—my eyesight has got worse."},
{"word":"prescription glasses","zh":"处方眼镜","pos":"n.","ipa":"","ex":"I wear prescription glasses for reading and working at a screen."},
{"word":"stress","zh":"压力","pos":"n.","ipa":"","ex":"Too much stress at work can have serious long-term health effects."},
{"word":"mental health","zh":"心理健康","pos":"n.","ipa":"","ex":"Looking after your mental health is just as important as your physical health."},
{"word":"meditation","zh":"冥想","pos":"n.","ipa":"","ex":"Ten minutes of meditation each morning helps me start the day calmly."},
{"word":"diet","zh":"饮食","pos":"n.","ipa":"","ex":"A balanced diet is the foundation of good long-term health."},
{"word":"hydration","zh":"补水","pos":"n.","ipa":"","ex":"Good hydration improves concentration, energy, and skin health."},
{"word":"vitamins","zh":"维生素","pos":"n.","ipa":"","ex":"Take vitamin D supplements if you don't get much sunlight."},
{"word":"blood sugar","zh":"血糖","pos":"n.","ipa":"","ex":"Diabetic patients must monitor their blood sugar levels daily."},
{"word":"surgery recovery","zh":"术后恢复","pos":"n.","ipa":"","ex":"Surgery recovery can take several weeks depending on the procedure."},

# ── 21. Clothes & Fashion (服装与时尚) ────────────────────────────────────
{"word":"outfit","zh":"全套服装","pos":"n.","ipa":"","ex":"She put together a stylish outfit for the business dinner."},
{"word":"suit","zh":"西装","pos":"n.","ipa":"","ex":"He always wears a suit to client meetings."},
{"word":"casual","zh":"休闲的","pos":"adj.","ipa":"","ex":"Friday is casual dress day at our office."},
{"word":"formal","zh":"正式的","pos":"adj.","ipa":"","ex":"The awards ceremony is formal, so dress accordingly."},
{"word":"size","zh":"尺码","pos":"n.","ipa":"","ex":"Do you have this jacket in a size large or extra-large?"},
{"word":"fit","zh":"合身的","pos":"adj.","ipa":"","ex":"This shirt fits perfectly—I'll take it."},
{"word":"tight","zh":"紧的","pos":"adj.","ipa":"","ex":"These trousers are a bit tight around the waist—do you have a bigger size?"},
{"word":"loose","zh":"宽松的","pos":"adj.","ipa":"","ex":"Loose, comfortable clothing is ideal for a long flight."},
{"word":"fabric","zh":"布料","pos":"n.","ipa":"","ex":"This fabric is 100% cotton, so it's breathable and soft."},
{"word":"laundry","zh":"洗衣","pos":"n.","ipa":"","ex":"Read the laundry label before washing to avoid shrinking."},
{"word":"iron","zh":"熨斗 / 熨烫","pos":"n./v.","ipa":"","ex":"Iron your shirt the night before to save time in the morning."},
{"word":"dry clean only","zh":"只可干洗","pos":"phr.","ipa":"","ex":"The label says dry clean only—don't put it in the washing machine."},
{"word":"wardrobe","zh":"衣橱 / 衣柜","pos":"n.","ipa":"","ex":"I need to declutter my wardrobe and donate clothes I no longer wear."},
{"word":"accessory","zh":"配饰","pos":"n.","ipa":"","ex":"A simple scarf or belt can really elevate a basic outfit."},
{"word":"dress code","zh":"着装规定","pos":"n.","ipa":"","ex":"Check the dress code before booking the restaurant—some require smart attire."},

# ── 22. Interpersonal & Communication (人际沟通) ──────────────────────────
{"word":"introduce","zh":"介绍","pos":"v.","ipa":"","ex":"Let me introduce you to our new marketing director."},
{"word":"shake hands","zh":"握手","pos":"phr.","ipa":"","ex":"It is customary to shake hands when meeting a client for the first time."},
{"word":"compliment","zh":"称赞","pos":"n./v.","ipa":"","ex":"She received many compliments on her thoughtful presentation."},
{"word":"apologise","zh":"道歉","pos":"v.","ipa":"","ex":"I'd like to sincerely apologise for the confusion I caused."},
{"word":"interrupt","zh":"打断","pos":"v.","ipa":"","ex":"I'm sorry to interrupt, but could I add a quick point?"},
{"word":"clarify","zh":"澄清","pos":"v.","ipa":"","ex":"Could you clarify what you mean by 'acceptable quality'?"},
{"word":"confirm","zh":"确认","pos":"v.","ipa":"","ex":"Please confirm your attendance by replying to this email."},
{"word":"remind","zh":"提醒","pos":"v.","ipa":"","ex":"I'll send a reminder email before the meeting tomorrow."},
{"word":"suggest","zh":"建议","pos":"v.","ipa":"","ex":"I suggest we take a short break and then continue."},
{"word":"recommend","zh":"推荐","pos":"v.","ipa":"","ex":"Could you recommend a good hotel near the conference venue?"},
{"word":"complain","zh":"投诉 / 抱怨","pos":"v.","ipa":"","ex":"Several guests complained about the slow service at the hotel."},
{"word":"argue","zh":"争论","pos":"v.","ipa":"","ex":"It's better to discuss calmly than to argue and damage the relationship."},
{"word":"persuade","zh":"说服","pos":"v.","ipa":"","ex":"She persuaded the team to adopt a more innovative approach."},
{"word":"encourage","zh":"鼓励","pos":"v.","ipa":"","ex":"Good managers always encourage their team members to grow."},
{"word":"negotiate","zh":"谈判 / 协商","pos":"v.","ipa":"","ex":"We negotiated a better price by ordering a larger quantity."},
{"word":"disagree politely","zh":"礼貌地表示不同意","pos":"phr.","ipa":"","ex":"I see your point, but I'd respectfully disagree with that view."},
{"word":"make a point","zh":"提出观点","pos":"phr.","ipa":"","ex":"I'd like to make a point about the project timeline."},
{"word":"keep in touch","zh":"保持联系","pos":"phr.","ipa":"","ex":"Let's keep in touch after the conference—here's my card."},
{"word":"reach out","zh":"主动联系","pos":"phr.v.","ipa":"","ex":"Don't hesitate to reach out if you have any questions at all."},
{"word":"get in touch","zh":"联系","pos":"phr.","ipa":"","ex":"Get in touch with the supplier and ask for a formal quotation."},
{"word":"touch base","zh":"联系确认","pos":"phr.","ipa":"","ex":"Let's touch base next week to see how things are progressing."},
{"word":"small talk","zh":"闲聊","pos":"n.","ipa":"","ex":"Making small talk before a meeting helps break the ice."},
{"word":"body language","zh":"肢体语言","pos":"n.","ipa":"","ex":"Good body language—eye contact and upright posture—builds trust."},
{"word":"tone of voice","zh":"语气","pos":"n.","ipa":"","ex":"Your tone of voice matters as much as the words you choose."},

# ── 23. Nature & Environment (自然与环境) ─────────────────────────────────
{"word":"ocean","zh":"海洋","pos":"n.","ipa":"","ex":"The ocean covers more than 70% of the Earth's surface."},
{"word":"river","zh":"河流","pos":"n.","ipa":"","ex":"We went kayaking down the river on a sunny afternoon."},
{"word":"forest","zh":"森林","pos":"n.","ipa":"","ex":"The ancient forest is home to hundreds of rare species."},
{"word":"desert","zh":"沙漠","pos":"n.","ipa":"","ex":"Temperatures in the Sahara Desert can exceed 50 degrees Celsius."},
{"word":"island","zh":"岛屿","pos":"n.","ipa":"","ex":"We spent a week on a beautiful tropical island."},
{"word":"earthquake","zh":"地震","pos":"n.","ipa":"","ex":"A major earthquake struck the region, causing widespread damage."},
{"word":"pollution","zh":"污染","pos":"n.","ipa":"","ex":"Air pollution in large cities is a serious public health concern."},
{"word":"environment","zh":"环境","pos":"n.","ipa":"","ex":"We all have a responsibility to protect the natural environment."},
{"word":"recycle","zh":"回收利用","pos":"v.","ipa":"","ex":"Recycle paper, glass, and plastic to reduce landfill waste."},
{"word":"renewable energy","zh":"可再生能源","pos":"n.","ipa":"","ex":"Solar and wind power are the fastest-growing forms of renewable energy."},
{"word":"carbon footprint","zh":"碳足迹","pos":"n.","ipa":"","ex":"Reducing your carbon footprint is one way to help slow climate change."},
{"word":"climate change","zh":"气候变化","pos":"n.","ipa":"","ex":"Climate change poses one of the greatest challenges of our generation."},
{"word":"wildlife","zh":"野生动物","pos":"n.","ipa":"","ex":"The national park protects a wide variety of endangered wildlife."},
{"word":"sustainability","zh":"可持续性","pos":"n.","ipa":"","ex":"Sustainability is now a core part of our company's business strategy."},

# ── 24. Numbers & Descriptions (数量与描述) ──────────────────────────────
{"word":"dozen","zh":"一打（12个）","pos":"n.","ipa":"","ex":"Please buy a dozen eggs on your way home from work."},
{"word":"per cent","zh":"百分之…","pos":"n.","ipa":"","ex":"Sales rose by 15 per cent compared to the same quarter last year."},
{"word":"double","zh":"两倍 / 双份","pos":"adj./v.","ipa":"","ex":"We need to double our output to meet the new contract demands."},
{"word":"average","zh":"平均","pos":"n./adj.","ipa":"","ex":"The average salary in this industry is around 15,000 yuan per month."},
{"word":"maximum","zh":"最大值 / 最多","pos":"n./adj.","ipa":"","ex":"The maximum weight limit for carry-on luggage is 7 kilograms."},
{"word":"minimum","zh":"最小值 / 最少","pos":"n./adj.","ipa":"","ex":"The minimum order quantity is 100 units for a bulk discount."},
{"word":"total","zh":"总计","pos":"n./adj.","ipa":"","ex":"The total cost, including tax and shipping, is 3,500 yuan."},
{"word":"increase","zh":"增加","pos":"v./n.","ipa":"","ex":"The company expects revenue to increase by 20% next year."},
{"word":"decrease","zh":"减少","pos":"v./n.","ipa":"","ex":"The number of complaints has decreased significantly this quarter."},
{"word":"significant","zh":"显著的","pos":"adj.","ipa":"","ex":"There has been a significant improvement in customer satisfaction scores."},
{"word":"slight","zh":"轻微的","pos":"adj.","ipa":"","ex":"There's been a slight delay, but we're still on schedule overall."},
{"word":"considerable","zh":"相当大的","pos":"adj.","ipa":"","ex":"Considerable effort went into making this event a success."},
{"word":"proportion","zh":"比例","pos":"n.","ipa":"","ex":"A large proportion of our customers now shop via mobile."},
{"word":"majority","zh":"大多数","pos":"n.","ipa":"","ex":"The majority of staff voted in favour of the new flexible policy."},
{"word":"minority","zh":"少数","pos":"n.","ipa":"","ex":"Only a small minority expressed concerns about the new arrangement."},

# ── 25. Common Adjectives & Verbs (常用形容词与动词) ────────────────────
{"word":"available","zh":"可用的 / 空闲的","pos":"adj.","ipa":"","ex":"Is this room available for the whole of next week?"},
{"word":"convenient","zh":"方便的","pos":"adj.","ipa":"","ex":"A location near the metro station would be very convenient."},
{"word":"essential","zh":"必要的","pos":"adj.","ipa":"","ex":"A good internet connection is essential for remote work."},
{"word":"appropriate","zh":"合适的","pos":"adj.","ipa":"","ex":"Please wear appropriate attire for the formal dinner."},
{"word":"sufficient","zh":"足够的","pos":"adj.","ipa":"","ex":"Please ensure there is sufficient time for questions at the end."},
{"word":"flexible","zh":"灵活的","pos":"adj.","ipa":"","ex":"Our working hours are flexible—you can start between 8 and 10."},
{"word":"relevant","zh":"相关的","pos":"adj.","ipa":"","ex":"Only relevant experience should be included in your CV."},
{"word":"accurate","zh":"准确的","pos":"adj.","ipa":"","ex":"Make sure all figures in the report are accurate and up to date."},
{"word":"reliable","zh":"可靠的","pos":"adj.","ipa":"","ex":"We need a reliable supplier who can deliver on time, every time."},
{"word":"efficient","zh":"高效的","pos":"adj.","ipa":"","ex":"The new system is far more efficient than the old paper-based process."},
{"word":"complicated","zh":"复杂的","pos":"adj.","ipa":"","ex":"The visa application process can be very complicated—seek advice."},
{"word":"straightforward","zh":"简单直接的","pos":"adj.","ipa":"","ex":"The instructions are clear and straightforward to follow."},
{"word":"arrange","zh":"安排","pos":"v.","ipa":"","ex":"I'll arrange a car to pick you up from the airport."},
{"word":"prepare","zh":"准备","pos":"v.","ipa":"","ex":"Prepare your questions in advance so you don't forget during the call."},
{"word":"manage","zh":"管理 / 设法做到","pos":"v.","ipa":"","ex":"She managed to finish the whole project ahead of schedule."},
{"word":"achieve","zh":"实现 / 达到","pos":"v.","ipa":"","ex":"We need to work together to achieve our ambitious growth targets."},
{"word":"improve","zh":"改善 / 提高","pos":"v.","ipa":"","ex":"Regular practice is the best way to improve your spoken English."},
{"word":"expand","zh":"扩展 / 扩大","pos":"v.","ipa":"","ex":"The company plans to expand into three new markets next year."},
{"word":"reduce","zh":"减少 / 降低","pos":"v.","ipa":"","ex":"We need to find ways to reduce costs without cutting quality."},
{"word":"maintain","zh":"维护 / 保持","pos":"v.","ipa":"","ex":"It is important to maintain regular contact with your key clients."},
{"word":"ensure","zh":"确保","pos":"v.","ipa":"","ex":"Please ensure that all safety guidelines are followed at all times."},
{"word":"consider","zh":"考虑","pos":"v.","ipa":"","ex":"We need to consider all options before making a final decision."},
{"word":"compare","zh":"比较","pos":"v.","ipa":"","ex":"Compare prices from at least three different suppliers before ordering."},
{"word":"discuss","zh":"讨论","pos":"v.","ipa":"","ex":"Let's schedule a call to discuss the details in full."},
{"word":"explain","zh":"解释","pos":"v.","ipa":"","ex":"Could you explain how the new billing system works?"},
{"word":"present","zh":"呈现 / 展示","pos":"v.","ipa":"","ex":"She will present the quarterly results to the board on Thursday."},
{"word":"address","zh":"处理 / 应对","pos":"v.","ipa":"","ex":"We need to address the customer complaint before it escalates."},
{"word":"identify","zh":"识别 / 找出","pos":"v.","ipa":"","ex":"Let's identify the root cause of the problem before proposing a fix."},
{"word":"implement","zh":"实施","pos":"v.","ipa":"","ex":"We plan to implement the new policy from the start of next month."},
{"word":"evaluate","zh":"评估","pos":"v.","ipa":"","ex":"We'll evaluate the pilot programme after three months."},
{"word":"monitor","zh":"监控 / 跟踪","pos":"v.","ipa":"","ex":"The team will monitor the results on a weekly basis."},
]

path = pathlib.Path(__file__).parent.parent / 'game' / 'daily-words-1000.json'
existing = json.loads(path.read_text(encoding='utf-8'))

existing_words = {e['word'] for e in existing}
added = 0
for entry in EXTRA:
    if entry['word'] not in existing_words:
        existing.append(entry)
        existing_words.add(entry['word'])
        added += 1

path.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding='utf-8')
print(f"Done. Added {added} new entries. Total: {len(existing)}")
