#!/usr/bin/env python3
"""
Optimize pet-words-1000.json:
  • Remove ~200 simplest/inappropriate words (web artifacts, proper nouns,
    duplicate inflected forms, A1-level basics)
  • Add ~200 harder B1/B2 words useful for PET exam
"""
import json, pathlib

DATA = pathlib.Path(__file__).parent.parent / 'game' / 'pet-words-1000.json'

# ── Words to REMOVE ───────────────────────────────────────────────────────────
REMOVE = {
    # web artifacts / inappropriate content
    "ebay", "google", "yahoo", "microsoft", "linux", "sponsored",
    "homepage", "login", "domain", "copyright", "casino", "poker",
    "porn", "nude", "lesbian", "teen", "teens",

    # pure proper nouns / place names / person names
    "africa", "australia", "california", "canada", "china", "florida",
    "india", "japan", "london", "texas", "washington", "york",
    "france", "germany", "america", "david", "james", "john",
    "michael", "robert",

    # duplicate plural / inflected forms (base form kept)
    "activities", "applications", "archives", "areas", "articles",
    "benefits", "books", "cases", "changes", "companies", "conditions",
    "costs", "countries", "customers", "downloads", "effects", "events",
    "features", "files", "forums", "friends", "games", "girls", "groups",
    "hours", "hotels", "images", "issues", "items", "lines", "links",
    "listings", "materials", "members", "messages", "methods", "minutes",
    "models", "months", "movies", "names", "needs", "notes", "offers",
    "orders", "parts", "photos", "pictures", "plans", "players", "points",
    "posts", "prices", "problems", "products", "programs", "projects",
    "questions", "rates", "records", "reports", "requirements", "resources",
    "results", "returns", "reviews", "rights", "rules", "sales", "schools",
    "sellers", "services", "shows", "sites", "solutions", "standards",
    "states", "stores", "stories", "students", "studies", "supplies",
    "systems", "terms", "topics", "types", "updated", "users", "values",
    "videos", "views", "words", "works", "years",

    # very basic A1 vocabulary
    "able", "about", "above", "after", "again", "already", "also",
    "always", "another", "away", "baby", "back", "because", "before",
    "below", "best", "better", "between", "black", "blue", "body", "both",
    "call", "care", "card", "cards", "cause", "check", "choose", "clear",
    "close", "could", "down", "each", "early", "east", "easy", "either",
    "else", "enough", "even", "ever", "every", "everything", "find",
    "first", "five", "follow", "four", "free", "full", "game", "getting",
    "going", "great", "green", "hand", "hard", "having", "head", "heart",
    "help", "high", "house", "into", "just", "keep", "kids", "know",
    "large", "last", "later", "left", "life", "light", "like", "live",
    "long", "love", "mail", "makes", "making", "might", "money", "must",
    "name", "need", "never", "next", "night", "nothing", "number",
    "often", "once", "only", "open", "other", "over", "page", "paper",
    "part", "past", "place", "play", "please", "plus", "point", "power",
    "print", "public", "quick", "quickly", "quiet", "rather", "read",
    "real", "really", "right", "road", "room", "said", "same", "save",
    "school", "score", "search", "second", "self", "sell", "send",
    "short", "should", "show", "side", "sign", "since", "simple", "some",
    "someone", "something", "sound", "south", "space", "staff", "star",
    "start", "still", "store", "story", "street", "student", "study",
    "stuff", "sure", "system", "table", "talk", "team", "test", "text",
    "than", "thanks", "then", "think", "thought", "through", "title",
    "today", "together", "total", "track", "true", "type", "under",
    "until", "used", "using", "usually", "value", "version", "video",
    "view", "visit", "want", "watch", "weather", "well", "west",
    "whether", "which", "while", "white", "whole", "will", "within",
    "women", "word", "would", "write", "writing", "young",
}

# ── Words to ADD (~200 B1/B2 words) ──────────────────────────────────────────
ADD = [
    # ── Verbs ─────────────────────────────────────────────────────────────────
    {"word": "accomplish",  "zh": "完成，实现",          "pos": "v"},
    {"word": "acknowledge", "zh": "承认，确认",          "pos": "v"},
    {"word": "adapt",       "zh": "适应，改编",          "pos": "v"},
    {"word": "alter",       "zh": "改变，修改",          "pos": "v"},
    {"word": "anticipate",  "zh": "预期，预料",          "pos": "v"},
    {"word": "appreciate",  "zh": "欣赏，感激",          "pos": "v"},
    {"word": "assess",      "zh": "评估，评价",          "pos": "v"},
    {"word": "assist",      "zh": "协助，帮助",          "pos": "v"},
    {"word": "assume",      "zh": "假设，承担",          "pos": "v"},
    {"word": "calculate",   "zh": "计算，估算",          "pos": "v"},
    {"word": "clarify",     "zh": "澄清，说明",          "pos": "v"},
    {"word": "collaborate", "zh": "合作，协作",          "pos": "v"},
    {"word": "comprehend",  "zh": "理解，领会",          "pos": "v"},
    {"word": "concentrate", "zh": "集中，专注",          "pos": "v"},
    {"word": "conclude",    "zh": "得出结论，结束",      "pos": "v"},
    {"word": "confirm",     "zh": "确认，证实",          "pos": "v"},
    {"word": "contribute",  "zh": "贡献，提供",          "pos": "v"},
    {"word": "convince",    "zh": "说服，使信服",        "pos": "v"},
    {"word": "cooperate",   "zh": "合作，配合",          "pos": "v"},
    {"word": "demonstrate", "zh": "演示，证明",          "pos": "v"},
    {"word": "determine",   "zh": "决定，确定",          "pos": "v"},
    {"word": "distinguish", "zh": "区分，辨别",          "pos": "v"},
    {"word": "elaborate",   "zh": "详细说明，精心制作",  "pos": "v"},
    {"word": "eliminate",   "zh": "消除，淘汰",          "pos": "v"},
    {"word": "emphasize",   "zh": "强调，着重",          "pos": "v"},
    {"word": "estimate",    "zh": "估计，估算",          "pos": "v"},
    {"word": "evaluate",    "zh": "评价，评估",          "pos": "v"},
    {"word": "examine",     "zh": "检查，审查",          "pos": "v"},
    {"word": "facilitate",  "zh": "促进，使便利",        "pos": "v"},
    {"word": "generate",    "zh": "产生，生成",          "pos": "v"},
    {"word": "hesitate",    "zh": "犹豫，迟疑",          "pos": "v"},
    {"word": "implement",   "zh": "实施，执行",          "pos": "v"},
    {"word": "indicate",    "zh": "表明，指示",          "pos": "v"},
    {"word": "interpret",   "zh": "解释，理解",          "pos": "v"},
    {"word": "investigate", "zh": "调查，研究",          "pos": "v"},
    {"word": "justify",     "zh": "证明正当，为…辩护",   "pos": "v"},
    {"word": "maintain",    "zh": "维持，保养",          "pos": "v"},
    {"word": "negotiate",   "zh": "谈判，协商",          "pos": "v"},
    {"word": "obtain",      "zh": "获得，得到",          "pos": "v"},
    {"word": "operate",     "zh": "操作，运行",          "pos": "v"},
    {"word": "perceive",    "zh": "感知，察觉",          "pos": "v"},
    {"word": "persist",     "zh": "坚持，持续",          "pos": "v"},
    {"word": "persuade",    "zh": "说服，劝说",          "pos": "v"},
    {"word": "predict",     "zh": "预测，预言",          "pos": "v"},
    {"word": "promote",     "zh": "促进，推广，晋升",    "pos": "v"},
    {"word": "propose",     "zh": "提议，建议",          "pos": "v"},
    {"word": "pursue",      "zh": "追求，追逐",          "pos": "v"},
    {"word": "recover",     "zh": "恢复，康复",          "pos": "v"},
    {"word": "resolve",     "zh": "解决，决定",          "pos": "v"},
    {"word": "restrict",    "zh": "限制，约束",          "pos": "v"},
    {"word": "retain",      "zh": "保留，记住",          "pos": "v"},
    {"word": "seek",        "zh": "寻求，寻找",          "pos": "v"},
    {"word": "stimulate",   "zh": "刺激，激励",          "pos": "v"},
    {"word": "strengthen",  "zh": "加强，增强",          "pos": "v"},
    {"word": "substitute",  "zh": "替代，代替",          "pos": "v"},
    {"word": "summarize",   "zh": "总结，概括",          "pos": "v"},
    {"word": "sustain",     "zh": "维持，支撑",          "pos": "v"},
    {"word": "transform",   "zh": "转变，改变",          "pos": "v"},
    {"word": "transmit",    "zh": "传递，传输",          "pos": "v"},
    {"word": "utilize",     "zh": "利用，使用",          "pos": "v"},
    {"word": "volunteer",   "zh": "自愿，做志愿者",      "pos": "v"},

    # ── Nouns ──────────────────────────────────────────────────────────────────
    {"word": "achievement", "zh": "成就，成绩",          "pos": "n"},
    {"word": "ambition",    "zh": "雄心，抱负",          "pos": "n"},
    {"word": "anxiety",     "zh": "焦虑，担忧",          "pos": "n"},
    {"word": "appreciation","zh": "欣赏，感激",          "pos": "n"},
    {"word": "approach",    "zh": "方法，途径",          "pos": "n"},
    {"word": "assumption",  "zh": "假设，假定",          "pos": "n"},
    {"word": "atmosphere",  "zh": "大气，气氛",          "pos": "n"},
    {"word": "attitude",    "zh": "态度，看法",          "pos": "n"},
    {"word": "awareness",   "zh": "意识，认识",          "pos": "n"},
    {"word": "barrier",     "zh": "障碍，屏障",          "pos": "n"},
    {"word": "capacity",    "zh": "能力，容量",          "pos": "n"},
    {"word": "challenge",   "zh": "挑战，质疑",          "pos": "n"},
    {"word": "characteristic","zh": "特征，特性",        "pos": "n"},
    {"word": "circumstance","zh": "情况，环境",          "pos": "n"},
    {"word": "commitment",  "zh": "承诺，投入",          "pos": "n"},
    {"word": "competence",  "zh": "能力，胜任",          "pos": "n"},
    {"word": "compromise",  "zh": "妥协，折中",          "pos": "n"},
    {"word": "confidence",  "zh": "信心，自信",          "pos": "n"},
    {"word": "conflict",    "zh": "冲突，矛盾",          "pos": "n"},
    {"word": "consequence", "zh": "后果，结果",          "pos": "n"},
    {"word": "consultation","zh": "咨询，商议",          "pos": "n"},
    {"word": "contribution","zh": "贡献，捐献",          "pos": "n"},
    {"word": "controversy", "zh": "争议，争论",          "pos": "n"},
    {"word": "cooperation", "zh": "合作，协作",          "pos": "n"},
    {"word": "criticism",   "zh": "批评，评论",          "pos": "n"},
    {"word": "curiosity",   "zh": "好奇心，奇特的事",    "pos": "n"},
    {"word": "dedication",  "zh": "奉献，专注",          "pos": "n"},
    {"word": "determination","zh": "决心，坚定",         "pos": "n"},
    {"word": "disappointment","zh": "失望，沮丧",        "pos": "n"},
    {"word": "diversity",   "zh": "多样性，多元化",      "pos": "n"},
    {"word": "donation",    "zh": "捐款，捐赠",          "pos": "n"},
    {"word": "doubt",       "zh": "怀疑，疑虑",          "pos": "n"},
    {"word": "economy",     "zh": "经济，节约",          "pos": "n"},
    {"word": "efficiency",  "zh": "效率，效能",          "pos": "n"},
    {"word": "emotion",     "zh": "情感，情绪",          "pos": "n"},
    {"word": "encouragement","zh": "鼓励，激励",         "pos": "n"},
    {"word": "enthusiasm",  "zh": "热情，热忱",          "pos": "n"},
    {"word": "evaluation",  "zh": "评估，评价",          "pos": "n"},
    {"word": "evidence",    "zh": "证据，证明",          "pos": "n"},
    {"word": "expectation", "zh": "期望，预期",          "pos": "n"},
    {"word": "frustration", "zh": "挫折，沮丧",          "pos": "n"},
    {"word": "guidance",    "zh": "指导，引导",          "pos": "n"},
    {"word": "impression",  "zh": "印象，感想",          "pos": "n"},
    {"word": "initiative",  "zh": "主动性，倡议",        "pos": "n"},
    {"word": "innovation",  "zh": "创新，革新",          "pos": "n"},
    {"word": "inspiration", "zh": "灵感，鼓舞",          "pos": "n"},
    {"word": "intelligence","zh": "智力，情报",          "pos": "n"},
    {"word": "interaction", "zh": "互动，交流",          "pos": "n"},
    {"word": "involvement", "zh": "参与，投入",          "pos": "n"},
    {"word": "jealousy",    "zh": "嫉妒，妒忌",          "pos": "n"},
    {"word": "judgment",    "zh": "判断，判决",          "pos": "n"},
    {"word": "kindness",    "zh": "善良，仁慈",          "pos": "n"},
    {"word": "leadership",  "zh": "领导力，领导",        "pos": "n"},
    {"word": "limitation",  "zh": "限制，局限性",        "pos": "n"},
    {"word": "motivation",  "zh": "动力，动机",          "pos": "n"},
    {"word": "necessity",   "zh": "必要性，需要",        "pos": "n"},
    {"word": "obligation",  "zh": "义务，责任",          "pos": "n"},
    {"word": "observation", "zh": "观察，评论",          "pos": "n"},
    {"word": "opportunity", "zh": "机会，时机",          "pos": "n"},
    {"word": "opposition",  "zh": "反对，对立",          "pos": "n"},
    {"word": "patience",    "zh": "耐心，忍耐",          "pos": "n"},
    {"word": "permission",  "zh": "许可，批准",          "pos": "n"},
    {"word": "perspective", "zh": "视角，观点",          "pos": "n"},
    {"word": "phenomenon",  "zh": "现象，奇迹",          "pos": "n"},
    {"word": "pollution",   "zh": "污染",                "pos": "n"},
    {"word": "potential",   "zh": "潜力，潜在的",        "pos": "n"},
    {"word": "poverty",     "zh": "贫困，贫穷",          "pos": "n"},
    {"word": "preference",  "zh": "偏好，喜好",          "pos": "n"},
    {"word": "prejudice",   "zh": "偏见，成见",          "pos": "n"},
    {"word": "pressure",    "zh": "压力，压迫",          "pos": "n"},
    {"word": "priority",    "zh": "优先权，重要性",      "pos": "n"},
    {"word": "privilege",   "zh": "特权，荣幸",          "pos": "n"},
    {"word": "procedure",   "zh": "程序，步骤",          "pos": "n"},
    {"word": "protest",     "zh": "抗议，反对",          "pos": "n"},
    {"word": "qualification","zh": "资格，条件",         "pos": "n"},
    {"word": "reaction",    "zh": "反应，回应",          "pos": "n"},
    {"word": "recognition", "zh": "认可，识别",          "pos": "n"},
    {"word": "reform",      "zh": "改革，改变",          "pos": "n"},
    {"word": "relationship","zh": "关系，联系",          "pos": "n"},
    {"word": "reputation",  "zh": "名誉，声望",          "pos": "n"},
    {"word": "responsibility","zh": "责任，职责",        "pos": "n"},
    {"word": "revenue",     "zh": "收入，税收",          "pos": "n"},
    {"word": "satisfaction","zh": "满意，满足",          "pos": "n"},
    {"word": "scandal",     "zh": "丑闻，非议",          "pos": "n"},
    {"word": "sensitivity", "zh": "敏感性，敏感度",      "pos": "n"},
    {"word": "shortage",    "zh": "短缺，不足",          "pos": "n"},
    {"word": "significance","zh": "重要性，意义",        "pos": "n"},
    {"word": "situation",   "zh": "情况，处境",          "pos": "n"},
    {"word": "stereotype",  "zh": "刻板印象，固有观念",  "pos": "n"},
    {"word": "strategy",    "zh": "策略，战略",          "pos": "n"},
    {"word": "structure",   "zh": "结构，构造",          "pos": "n"},
    {"word": "suggestion",  "zh": "建议，暗示",          "pos": "n"},
    {"word": "sympathy",    "zh": "同情，同感",          "pos": "n"},
    {"word": "tendency",    "zh": "倾向，趋势",          "pos": "n"},
    {"word": "tradition",   "zh": "传统，惯例",          "pos": "n"},
    {"word": "transition",  "zh": "过渡，转变",          "pos": "n"},
    {"word": "trust",       "zh": "信任，信赖",          "pos": "n"},
    {"word": "uncertainty", "zh": "不确定，疑虑",        "pos": "n"},
    {"word": "variation",   "zh": "变化，差异",          "pos": "n"},
    {"word": "welfare",     "zh": "福利，幸福",          "pos": "n"},
    {"word": "wisdom",      "zh": "智慧，判断力",        "pos": "n"},

    # ── Adjectives ─────────────────────────────────────────────────────────────
    {"word": "ambitious",      "zh": "有雄心的，渴望成功的",   "pos": "adj"},
    {"word": "beneficial",     "zh": "有益的，有利的",         "pos": "adj"},
    {"word": "capable",        "zh": "有能力的，能干的",       "pos": "adj"},
    {"word": "cautious",       "zh": "谨慎的，小心的",         "pos": "adj"},
    {"word": "competitive",    "zh": "竞争的，有竞争力的",     "pos": "adj"},
    {"word": "complex",        "zh": "复杂的，综合的",         "pos": "adj"},
    {"word": "confident",      "zh": "自信的，确信的",         "pos": "adj"},
    {"word": "consistent",     "zh": "一致的，始终如一的",     "pos": "adj"},
    {"word": "controversial",  "zh": "有争议的，引起争论的",   "pos": "adj"},
    {"word": "cooperative",    "zh": "合作的，配合的",         "pos": "adj"},
    {"word": "creative",       "zh": "有创造力的，创意的",     "pos": "adj"},
    {"word": "critical",       "zh": "批评性的，关键的",       "pos": "adj"},
    {"word": "dedicated",      "zh": "专注的，有奉献精神的",   "pos": "adj"},
    {"word": "determined",     "zh": "坚定的，有决心的",       "pos": "adj"},
    {"word": "diverse",        "zh": "多样的，不同的",         "pos": "adj"},
    {"word": "efficient",      "zh": "高效的，有效率的",       "pos": "adj"},
    {"word": "enthusiastic",   "zh": "热情的，热心的",         "pos": "adj"},
    {"word": "essential",      "zh": "必要的，本质的",         "pos": "adj"},
    {"word": "exceptional",    "zh": "特别的，卓越的",         "pos": "adj"},
    {"word": "flexible",       "zh": "灵活的，可变通的",       "pos": "adj"},
    {"word": "formal",         "zh": "正式的，规范的",         "pos": "adj"},
    {"word": "fundamental",    "zh": "基本的，重要的",         "pos": "adj"},
    {"word": "genuine",        "zh": "真实的，真诚的",         "pos": "adj"},
    {"word": "gradual",        "zh": "逐渐的，渐进的",         "pos": "adj"},
    {"word": "grateful",       "zh": "感激的，感谢的",         "pos": "adj"},
    {"word": "humble",         "zh": "谦虚的，谦逊的",         "pos": "adj"},
    {"word": "inevitable",     "zh": "不可避免的，必然的",     "pos": "adj"},
    {"word": "innovative",     "zh": "创新的，有创意的",       "pos": "adj"},
    {"word": "intense",        "zh": "强烈的，紧张的",         "pos": "adj"},
    {"word": "logical",        "zh": "合乎逻辑的，理性的",     "pos": "adj"},
    {"word": "moderate",       "zh": "适度的，温和的",         "pos": "adj"},
    {"word": "motivated",      "zh": "有动力的，积极进取的",   "pos": "adj"},
    {"word": "mutual",         "zh": "相互的，共同的",         "pos": "adj"},
    {"word": "neutral",        "zh": "中立的，中性的",         "pos": "adj"},
    {"word": "objective",      "zh": "客观的，目标",           "pos": "adj"},
    {"word": "obvious",        "zh": "明显的，显而易见的",     "pos": "adj"},
    {"word": "optional",       "zh": "可选的，非必须的",       "pos": "adj"},
    {"word": "passionate",     "zh": "热情的，充满激情的",     "pos": "adj"},
    {"word": "persistent",     "zh": "坚持不懈的，固执的",     "pos": "adj"},
    {"word": "physical",       "zh": "身体的，物理的",         "pos": "adj"},
    {"word": "practical",      "zh": "实际的，实用的",         "pos": "adj"},
    {"word": "precise",        "zh": "精确的，准确的",         "pos": "adj"},
    {"word": "productive",     "zh": "高产的，富有成效的",     "pos": "adj"},
    {"word": "qualified",      "zh": "有资格的，合格的",       "pos": "adj"},
    {"word": "radical",        "zh": "根本的，极端的",         "pos": "adj"},
    {"word": "rational",       "zh": "理性的，合理的",         "pos": "adj"},
    {"word": "reasonable",     "zh": "合理的，适度的",         "pos": "adj"},
    {"word": "relevant",       "zh": "相关的，有关的",         "pos": "adj"},
    {"word": "reliable",       "zh": "可靠的，可信赖的",       "pos": "adj"},
    {"word": "sensitive",      "zh": "敏感的，体贴的",         "pos": "adj"},
    {"word": "significant",    "zh": "重要的，有意义的",       "pos": "adj"},
    {"word": "straightforward","zh": "直接的，简单的",         "pos": "adj"},
    {"word": "sufficient",     "zh": "充足的，足够的",         "pos": "adj"},
    {"word": "temporary",      "zh": "暂时的，临时的",         "pos": "adj"},
    {"word": "thorough",       "zh": "彻底的，周密的",         "pos": "adj"},
    {"word": "thoughtful",     "zh": "体贴的，考虑周到的",     "pos": "adj"},
    {"word": "tolerant",       "zh": "宽容的，包容的",         "pos": "adj"},
    {"word": "unique",         "zh": "独特的，唯一的",         "pos": "adj"},
    {"word": "urgent",         "zh": "紧急的，迫切的",         "pos": "adj"},
    {"word": "versatile",      "zh": "多才多艺的，万能的",     "pos": "adj"},
    {"word": "vulnerable",     "zh": "脆弱的，易受伤的",       "pos": "adj"},
    {"word": "widespread",     "zh": "广泛的，普遍的",         "pos": "adj"},
]

# ── Process ───────────────────────────────────────────────────────────────────
original = json.load(open(DATA))
original_words = {x['word'] for x in original}

# Filter out removed words
kept = [x for x in original if x['word'] not in REMOVE]
removed = [x['word'] for x in original if x['word'] in REMOVE]

# Deduplicate ADD list against existing (after removal)
kept_words = {x['word'] for x in kept}
to_add = [x for x in ADD if x['word'] not in kept_words]

# Normalise add entries to match schema
for entry in to_add:
    entry.setdefault('ipa', '')

combined = kept + to_add

# ── Report ────────────────────────────────────────────────────────────────────
print(f"Original count : {len(original)}")
print(f"Removed        : {len(removed)}")
not_found = [w for w in REMOVE if w not in original_words]
if not_found:
    print(f"  (not found in original: {not_found})")
print(f"Added          : {len(to_add)}")
print(f"Final count    : {len(combined)}")

# Write
with open(DATA, 'w', encoding='utf-8') as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)
print("Done. Written to", DATA)
